<?php
/**
 * @file
 * Code for the Enterprise Satisfaction Survey feature.
 */

include_once 'enterprise_satsurvey.features.inc';


/**
 *  Implements of hook_menu()
 */
function enterprise_satsurvey_menu() {
  $items = array();

  $items['satsurvey/util'] = array(
    'title' => 'Sat Survey Util',
    'page callback' => 'enterprise_satsurvey_util',
    'access callback' => 'user_access',
    'access arguments' => array('admin intel'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function enterprise_satsurvey_util() {
  $info = system_get_info('module', 'webform');
  dsm($info);
  return 'OK';
}
