<?php


/**
 *  Implements of hook_menu()
 */
function intel_realtime_menu() {
  $items = array();
  $items['intel/author_load_js'] = array(
    'title' => '',
    'page callback' => 'intel_realtime_author_load_js',
    'access callback' => 'user_access',
    'access arguments' => array('view all intel reports'),
    'type' => MENU_CALLBACK,
  );
  $items['intel/content_type_load_js'] = array(
    'title' => '',
    'page callback' => 'intel_realtime_content_type_load_js',
    'access callback' => 'user_access',
    'access arguments' => array('view all intel reports'),
    'type' => MENU_CALLBACK,
  );
  $items['intel/term_load_js'] = array(
    'title' => '',
    'page callback' => 'intel_realtime_term_load_js',
    'access callback' => 'user_access',
    'access arguments' => array('view all intel reports'),
    'type' => MENU_CALLBACK,
  );
  $items['intel/visitor_load_js'] = array(
    'title' => '',
    'page callback' => 'intel_realtime_visitor_load_js',
    'access callback' => 'user_access',
    'access arguments' => array('view all intel reports'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/reports/intel/realtime'] = array(
      'title' => 'Realtime',
      'page callback' => 'intel_realtime_dashboard_report_page',
      'access callback' => 'user_access',
      'access arguments' => array('view all intel reports'),
      'type' => MENU_LOCAL_TASK,
      'weight' => 1,
      //'file' => 'reports/intel.report_scorecard.inc',
  );
  return $items;
}



function intel_realtime_author_load_js() {
  $response = array();
  if (empty($_GET['uid'])) {
    intel_json_output_error(INTEL_STATUS_BAD_REQUEST);
  }
  $account = user_load($_GET['uid']);
  if (empty($account)) {
    intel_json_output_error(INTEL_STATUS_NOT_FOUND);
  }
  $response['author'] = array();
  $response['author']['name'] = format_username($account);
  //$response['author']['account'] = $account;
  intel_json_output($response);
}

function intel_realtime_content_type_load_js() {
  $response = array();
  if (empty($_GET['type'])) {
    intel_json_output_error(INTEL_STATUS_BAD_REQUEST);
  }
  $types = node_type_get_types();
  $type = '';
  if (isset($types[$_GET['type']])) {
    $type = $types[$_GET['type']];
  }
  else if (isset($types['enterprise_' . $_GET['type']])) {
    $type = $types['enterprise_' . $_GET['type']];
  }

  if (!$type) {
    intel_json_output_error(INTEL_STATUS_NOT_FOUND);
  }
  $response['content_type'] = array();
  $response['content_type']['name'] = $type->name;
  //$response['author']['account'] = $account;
  intel_json_output($response);
}

function intel_realtime_term_load_js() {
  $response = array();
  if (empty($_GET['tid'])) {
    intel_json_output_error(INTEL_STATUS_BAD_REQUEST);
  }
  $term = taxonomy_term_load($_GET['tid']);
  if (empty($term)) {
    intel_json_output_error(INTEL_STATUS_NOT_FOUND);
  }
  $response['term'] = array();
  $response['term']['name'] = $term->name;
  //$response['author']['account'] = $account;
  intel_json_output($response);
}

function intel_realtime_visitor_load_js() {
  $response = array();
  if (empty($_GET['vtk'])) {
    intel_json_output_error(INTEL_STATUS_BAD_REQUEST);
  }
  $visitor = intel_visitor_load($_GET['vtk']);
  if (empty($visitor)) {
    intel_json_output_error(INTEL_STATUS_NOT_FOUND);
  }

  $response['visitor'] = $visitor->data;
  $response['visitor']['name'] = $visitor->name;
  $response['visitor']['vid'] = (int)$visitor->vid;
  intel_json_output($response);
}

function intel_json_output($data, $message = '') {
  $response = $data;
  $response['status'] = INTEL_STATUS_OK;
  if ($message) {
    $response['message'] = $message;
  }
  drupal_json_output($response);
  exit;
}

function intel_json_output_error($status, $message = '') {
  $response['status'] = $status;
  if ($message) {
    $response['message'] = $message;
  }
  drupal_json_output($response);
  exit;
}

function intel_realtime_dashboard_report_page() {
  global $base_path;
  $realtime_path = $base_path . intel_get_library_path() . '/realtime';
  $timeline_path = $base_path . libraries_get_path('TimelineJS');

  $js = array();

  // add jquery ui
  $js[] = 'http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js';
  $js[] = '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js';

  // add google jsapi
  $js[] = 'https://www.google.com/jsapi';

  // add timeline libs
  $js[] = $timeline_path . '/compiled/js/storyjs-embed.js';
  $js[] = $timeline_path . '/compiled/js/timeline-intel.js';

  // add realtime dashboard libs
  $js[] = $realtime_path . '/reports/js/lib.js';
  $js[] = $realtime_path . '/reports/js/rtd.model.js';
  $js[] = $realtime_path . '/reports/js/rtd.view.js';
  $js[] = $realtime_path . '/reports/js/rtd.config.js';

  $filepath = variable_get('intel_visitor_default_image_path', '');
  if (empty($filepath)) {
    $filepath = variable_get('user_picture_default', '');
  }
  if (!$filepath) {
    $filepath = $base_path . intel_get_library_path() . '/images/default_user.png';
  }

  require_once './' . drupal_get_path('module', 'intel') . "/includes/intel.ga.inc";
  $vaInfo = intel_get_visitor_attributes();

  $settings = array(
    'cmsPath' => $base_path,
    'apiPath' => $realtime_path,
    'dataPath' => $base_path . 'intel',
    'imgPath' => $base_path . intel_get_library_path() . '/images',
    'defaultVisitorImg' => $filepath,
    'icons' => array(
      'link-ext' => 'icon-link-ext',
      'link-ext-alt' => 'icon-link-ext-alt',
    ),
    'vaInfo' => $vaInfo,
  );

  $css = array();
  $css[] = 'http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Dancing+Script|Antic+Slab';

  // add dashboard styling
  $css[] = $realtime_path . '/reports/css/rtd-layout.css';
  $css[] = $realtime_path . '/reports/css/rtd-colors-archer.css';

  $css[] = $base_path . intel_get_library_path() . '/icons/css/intel.css';

  $output = '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">' . "\n";
  $output .= '<html>' . "\n";
  $output .= '<head>' . "\n";
  $output .= '  <title>Open Enterprise Intelligence</title>' . "\n";
  $output .= '  <script>' . "\n";
  $output .= '    rtdSettings = ' . json_encode($settings) . "\n";
  $output .= '  </script>' . "\n";
  foreach ($js AS $j) {
    $output .= '  <script src="' . $j . '"></script>' . "\n";
  }

  foreach ($css AS $c) {
    $output .= '  <link href="' . $c . '"  rel="stylesheet" type="text/css">' . "\n";
  }

  $output .= '</head>' . "\n";
  $output .= '<body>' . "\n";
  $output .= '</body>' . "\n";
  $output .= '</html>' . "\n";
  print $output;
  exit;

}