<?php
/**
 * @file
 * Code for the oedemo feature.
 */

include_once 'oedemo.features.inc';
/**
 * Implements hook_enterprise_apps_app_enabled()
 */
function oedemo_enterprise_apps_app_enabled() {
  enterprise_apps_config_app('oedemo');
}


function oedemo_enterprise_apps_config_settings() {
  $settings = array(
    'oedemo' => array(
      'nodes' => array(),
    ),
  );

  $nodes = array();
  // Mailchimp webform component for Website Success form
  $nodes['1fe8ec6e-050d-4e4f-9204-f0cba8085b7f'] = array(
    'webform' => array(
      'components' => array(
        0 => array(
          'nid' => 14,
          'cid' => 5,
          'pid' => 0,
          'form_key' => 'email_updates',
          'name' => 'Email updates',
          'type' => 'mailchimp',
          'value' => '',
          'extra' => array(
            'mailchimp_list' => '70298b4268',
            'use_existing_email_field' => 'email',
            'checkbox_label' => 'Subscribe to updates',
            'checkbox_checked_by_default' => 1,
            'checkbox_hidden' => 1,
            'mergefields' => 'FNAME|first_name
LNAME|last_name',
            'title_display' => 'before',
            'private' => 0,
            'conditional_operator' => '=',
            'field_prefix' => '',
            'field_suffix' => '',
            'description' => '',
            'attributes' => array(),
            'conditional_component' => '',
            'conditional_values' => '',
          ),
          'mandatory' => 0,
          'weight' => 4,
          'page_num' => 1,
        ),
      )
    )
  );
  // duplicate on Internet Marketing form
  $nodes['1aa7b3ac-74a1-4099-8015-1ef579add761'] = $nodes['1fe8ec6e-050d-4e4f-9204-f0cba8085b7f'];
  // duplicate on Internet Marketing form
  $nodes['ed36ec72-9393-4f7a-8418-4571024f07c4'] = $nodes['1fe8ec6e-050d-4e4f-9204-f0cba8085b7f'];
  // dup on contact form with modification
  $nodes['cf3a4aa8-a24a-4bac-af77-76b77020fa1d'] = $nodes['1fe8ec6e-050d-4e4f-9204-f0cba8085b7f'];
  $nodes['cf3a4aa8-a24a-4bac-af77-76b77020fa1d']['webform']['components'][0]['extra']['checkbox_hidden'] = 0;

  $settings['oedemo']['nodes'] = $nodes;

  return $settings;
}