<?php
/**
 * @file
 * Code for the Enterprise Demo feature.
 */

include_once 'enterprise_demo_config.features.inc';

/**
 * Implements hook_enterprise_apps_enable()
 */
function enterprise_demo_config_enterprise_apps_app_enabled() {
  enterprise_apps_config_app('enterprise_demo');
}

/*
 * Implements hook_enterprise_apps_config_settings()
 *
 * Finish field_instances and other items on content types & entities before
 * content is imported.
 */
function enterprise_demo_config_enterprise_apps_config_settings() {
  $edition = openenterprise_get_edition();


  $entity_info = array();
  $blocks = array();
  $variables = array();

  $base_field_instance = array(
    'field_cta_category' => 1,
    'field_intel_event_col' => 1,
    'field_keywords' => 1,
    'field_page_attribute_col' => 1,
    'field_visitor_attribute_col' => 1,
  );

  $base_field_group = array(
  );

  $rel_field_instance = array();
  $rel_field_group = array();

  $master_rel_info = enterprise_apps_get_entity_rel_info();
  foreach ($master_rel_info['field_instance'] as $k => $v) {
    $rel_field_instance[$k] = 1;
  }
  foreach ($master_rel_info['field_group'] as $k => $v) {
    $rel_field_group[$k] = $v;
  }

  //$entity_info = array();
  // array_merged is used becasue + operator was acting as pointer and changing
  // settings in $rel_field_group
  $entity_info['node:enterprise_blog'] = array();
  $entity_info['node:enterprise_blog']['field_instance'] = $base_field_instance + $rel_field_instance;
  $entity_info['node:enterprise_blog']['field_group'] = $base_field_group + $master_rel_info['field_group'];

  // TODO: something totally weird. Changing the entity_info is changing data on $rel_field_group.
  // Work on this later, wasting too much time.
  // open rel subject fieldset on blog
  //dsm($rel_field_group['group_rel_subject']->format_settings['formatter']);
  //$entity_info['node:enterprise_blog']['field_group']['group_rel_subject']->format_settings['formatter'] = 'collapsible';
  //dsm($rel_field_group['group_rel_subject']->format_settings['formatter']);

  $entity_info['node:enterprise_landingpage'] = array(
    'field_instance' => array(
      //'field_cta_category' => 1,
      'field_intel_event_col' => 1,
      'field_keywords' => 1,
      'field_page_attribute_col' => 1,
      'field_visitor_attribute_col' => 1,
    ) + $rel_field_instance,
    'field_group' => $base_field_group + $master_rel_info['field_group'],
  );

  $entity_info['node:enterprise_thankyou'] = array(
    'field_instance' => array(
      //'field_cta_category' => 1,
      'field_intel_event_col' => 1,
      'field_keywords' => 1,
      'field_page_attribute_col' => 1,
      'field_visitor_attribute_col' => 1,
    ) + $rel_field_instance,
    'field_group' => $base_field_group + $master_rel_info['field_group'],
  );

  $entity_info['node:page'] = array(
    'field_instance' => $base_field_instance + $rel_field_instance,
    'field_group' => $base_field_group + $master_rel_info['field_group'],
  );

  $entity_info['node:webform'] = array(
    'field_instance' => array(
      //'field_cta_category' => 1,
      'field_intel_event_col' => 1,
      'field_keywords' => 1,
      'field_page_attribute_col' => 1,
      'field_visitor_attribute_col' => 1,
    ) + $rel_field_instance,
    'field_group' => $base_field_group + $master_rel_info['field_group'],
  );

  if (module_exists('enterprise_work_config')) {
    $views_block_visibility = array();
    $entity_info['node:enterprise_work'] = array();
    $entity_info['node:enterprise_work']['field_instance'] = $base_field_instance + $rel_field_instance;
    $entity_info['node:enterprise_work']['field_group'] = $base_field_group + $master_rel_info['field_group'];

    // open rel services fieldset on work
    //$entity_info['node:enterprise_work']['field_group']['group_rel_service']['format_settings']['formatter'] = 'collapsible';

    $views_block_visibility[] = 'enterprise_work:page';

    if (module_exists('enterprise_client_config')) {
      $entity_info['node:enterprise_client'] = array(
        'field_instance' => $base_field_instance,
        'field_group' => $base_field_group + $master_rel_info['field_group'],
      );
      // open rel organization fieldset on client
      //$entity_info['node:enterprise_client']['field_group']['group_rel_organization']['format_settings']['formatter'] = 'collapsible';

      $views_block_visibility[] = 'enterprise_client:page';
    }

    if (module_exists('enterprise_testimonial_config')) {
      $entity_info['node:enterprise_testimonial'] = array(
        'field_instance' => $base_field_instance,
        'field_group' => $base_field_group + $master_rel_info['field_group'],
      );
      $views_block_visibility[] = 'enterprise_client:page';
    }

    $blocks['enterprise_rel:views_facet_filter'] = array(
      'title' => t('Filter by'),
      'regions' => array(
        'sidebar_second',
      ),
      'views' => array(
        'views' => $views_block_visibility,
      ),
      'weight' => 1,
    );
  }


  $settings = array(
    'enterprise_demo' => array(
      'entity_info' => $entity_info,
      'blocks' => $blocks,
      'variables' => $variables,
    ),
  );

  return $settings;
}

