<?php
/**
 * @file
 * enterprise_faq_content.features.uuid_entities.inc
 */

/**
 * Implements hook_uuid_default_entities().
 */
function enterprise_faq_content_uuid_default_entities() {
  $entities = array();

  $entities['enterprise_faq_content'][] = (object) array(
    '__metadata' => array(
      'type' => 'node',
      'uri' => 'node/567c48b4-3711-4834-97f1-fec2c9d9af69',
      'cause' => FALSE,
    ),
    'body' => array(
      'und' => array(
        0 => array(
          'format' => 'full_html',
          'summary' => '',
          'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec egestas justo. Mauris lorem justo, pellentesque id feugiat ut, malesuada tristique eros. Nunc varius quis metus vel bibendum. Nunc leo orci, convallis vel metus ac, auctor auctor metus. Suspendisse rutrum, enim ut posuere dignissim, enim erat tincidunt sem, nec venenatis mauris nunc ut massa. Fusce volutpat mi et nisl volutpat, pharetra vehicula eros placerat. Vestibulum placerat volutpat pretium.</p>
',
        ),
      ),
    ),
    'cid' => 0,
    'comment' => 1,
    'comment_count' => 0,
    'entity_type' => 'node',
    'field_categories' => array(),
    'language' => 'und',
    'last_comment_name' => NULL,
    'last_comment_uid' => 1,
    'log' => '',
    'metatags' => array(),
    'promote' => 0,
    'slug' => 'how_do_i_submit_a_support_request_',
    'status' => 1,
    'sticky' => 0,
    'title' => 'How do I submit a support request?',
    'tnid' => 0,
    'translate' => 0,
    'type' => 'enterprise_faq',
    'uid' => 1,
    'url_alias' => array(
      0 => array(
        'alias' => 'how-do-i-submit-support-request',
        'language' => 'und',
      ),
    ),
    'uuid' => '567c48b4-3711-4834-97f1-fec2c9d9af69',
  );
  $entities['enterprise_faq_content'][] = (object) array(
    '__metadata' => array(
      'type' => 'node',
      'uri' => 'node/b877d816-823c-4b14-9eb4-6f228eecca4b',
      'cause' => FALSE,
    ),
    'body' => array(
      'und' => array(
        0 => array(
          'format' => 'full_html',
          'summary' => '',
          'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec egestas justo. Mauris lorem justo, pellentesque id feugiat ut, malesuada tristique eros. Nunc varius quis metus vel bibendum. Nunc leo orci, convallis vel metus ac, auctor auctor metus. Suspendisse rutrum, enim ut posuere dignissim, enim erat tincidunt sem, nec venenatis mauris nunc ut massa. Fusce volutpat mi et nisl volutpat, pharetra vehicula eros placerat. Vestibulum placerat volutpat pretium.</p>
',
        ),
      ),
    ),
    'cid' => 0,
    'comment' => 1,
    'comment_count' => 0,
    'entity_type' => 'node',
    'field_categories' => array(),
    'language' => 'und',
    'last_comment_name' => NULL,
    'last_comment_uid' => 1,
    'log' => '',
    'metatags' => array(),
    'promote' => 0,
    'slug' => 'what_is_drupal_',
    'status' => 1,
    'sticky' => 0,
    'title' => 'What is Drupal?',
    'tnid' => 0,
    'translate' => 0,
    'type' => 'enterprise_faq',
    'uid' => 1,
    'url_alias' => array(
      0 => array(
        'alias' => 'what-drupal',
        'language' => 'und',
      ),
    ),
    'uuid' => 'b877d816-823c-4b14-9eb4-6f228eecca4b',
  );
  $entities['enterprise_faq_content'][] = (object) array(
    '__metadata' => array(
      'type' => 'node',
      'uri' => 'node/103db178-d002-4cd4-a63b-4752c665717b',
      'cause' => FALSE,
    ),
    'body' => array(
      'und' => array(
        0 => array(
          'format' => 'full_html',
          'summary' => '',
          'value' => '<p><span style="font-size: 15px; line-height: 21.428571701049805px; background-color: rgb(255, 255, 255);">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec egestas justo. Mauris lorem justo, pellentesque id feugiat ut, malesuada tristique eros. Nunc varius quis metus vel bibendum. Nunc leo orci, convallis vel metus ac, auctor auctor metus. Suspendisse rutrum, enim ut posuere dignissim, enim erat tincidunt sem, nec venenatis mauris nunc ut massa. Fusce volutpat mi et nisl volutpat, pharetra vehicula eros placerat. Vestibulum placerat volutpat pretium.</span></p>

<p><span style="font-size: 15px; line-height: 21.428571701049805px; background-color: rgb(255, 255, 255);">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec egestas justo. Mauris lorem justo, pellentesque id feugiat ut, malesuada tristique eros. Nunc varius quis metus vel bibendum. Nunc leo orci, convallis vel metus ac, auctor auctor metus. Suspendisse rutrum, enim ut posuere dignissim, enim erat tincidunt sem, nec venenatis mauris nunc ut massa. Fusce volutpat mi et nisl volutpat, pharetra vehicula eros placerat. Vestibulum placerat volutpat pretium.</span></p>
',
        ),
      ),
    ),
    'cid' => 0,
    'comment' => 1,
    'comment_count' => 0,
    'entity_type' => 'node',
    'field_categories' => array(),
    'language' => 'und',
    'last_comment_name' => NULL,
    'last_comment_uid' => 1,
    'log' => '',
    'metatags' => array(),
    'promote' => 0,
    'slug' => 'where_can_i_download_oe_intel_',
    'status' => 1,
    'sticky' => 0,
    'title' => 'Where can I download OE Intel?',
    'tnid' => 0,
    'translate' => 0,
    'type' => 'enterprise_faq',
    'uid' => 1,
    'url_alias' => array(
      0 => array(
        'alias' => 'where-can-i-download-oe-intel',
        'language' => 'und',
      ),
    ),
    'uuid' => '103db178-d002-4cd4-a63b-4752c665717b',
  );
  $entities['enterprise_faq_content'][] = (object) array(
    '__metadata' => array(
      'type' => 'node',
      'uri' => 'node/866ff9e8-32cd-4536-95f6-0ae48629a1b2',
      'cause' => FALSE,
    ),
    'body' => array(
      'und' => array(
        0 => array(
          'format' => 'full_html',
          'summary' => '',
          'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec egestas justo. Mauris lorem justo, pellentesque id feugiat ut, malesuada tristique eros. Nunc varius quis metus vel bibendum. Nunc leo orci, convallis vel metus ac, auctor auctor metus. Suspendisse rutrum, enim ut posuere dignissim, enim erat tincidunt sem, nec venenatis mauris nunc ut massa. Fusce volutpat mi et nisl volutpat, pharetra vehicula eros placerat. Vestibulum placerat volutpat pretium.</p>

<p><br />
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec egestas justo. Mauris lorem justo, pellentesque id feugiat ut, malesuada tristique eros. Nunc varius quis metus vel bibendum. Nunc leo orci, convallis vel metus ac, auctor auctor metus. Suspendisse rutrum, enim ut posuere dignissim, enim erat tincidunt sem, nec venenatis mauris nunc ut massa. Fusce volutpat mi et nisl volutpat, pharetra vehicula eros placerat. Vestibulum placerat volutpat pretium.<br />
&nbsp;</p>
',
        ),
      ),
    ),
    'cid' => 0,
    'comment' => 1,
    'comment_count' => 0,
    'entity_type' => 'node',
    'field_categories' => array(),
    'language' => 'und',
    'last_comment_name' => NULL,
    'last_comment_uid' => 1,
    'log' => '',
    'metatags' => array(),
    'promote' => 0,
    'slug' => 'how_does_your_invoicing_work_',
    'status' => 1,
    'sticky' => 0,
    'title' => 'How does your invoicing work?',
    'tnid' => 0,
    'translate' => 0,
    'type' => 'enterprise_faq',
    'uid' => 1,
    'url_alias' => array(
      0 => array(
        'alias' => 'how-does-your-invoicing-work',
        'language' => 'und',
      ),
    ),
    'uuid' => '866ff9e8-32cd-4536-95f6-0ae48629a1b2',
  );

  return $entities;
}
