<?php
/**
 * @file
 * Code for the Enterprise landing pages feature.
 */

include_once 'enterprise_conversion_config.features.inc';

/**
 * Implements hook_enterprise_apps_app_enabled()
 */
function enterprise_conversion_config_enterprise_apps_app_enabled() {
  enterprise_apps_config_app('enterprise_conversion');
}

function enterprise_conversion_config_enterprise_apps_config_settings() {
  $settings = array(
    'enterprise_conversion' => array(),
  );

  $settings['enterprise_conversion']['blocks'] = array(
    // add forms selector to landing page
    'cta:sel_cta_forms' => array(
      'regions' => array(
        'sidebar_second',
      ),
      'node_type' => array(
        'types' => array(
          'enterprise_landingpage',
        ),
      ),
      'weight' => 0,
    ),
    'cta:sel_cta_sidebar' => array(
      'path' => array(
        'pages' => array(
          'admin/*',
        ),
        'visibility' => 0,
      ),
      'weight' => 0,
    ),
    'cta:sel_cta_footer' => array(
      'path' => array(
        'pages' => array(
          'admin/*',
        ),
        'visibility' => 0,
      ),
      'weight' => 10,
      'css_class' => 'm-y-1',
    ),
    'views:enterprise_landingpage_blocks-rel_cta_sidebar' => array(
      'title' => '<none>',
      'cta' => array(
        'list_visibility' => 1,
        'selectors' => array(
          0 => 'cta_sidebar',
        ),
        'categories' => array(),
        'data' => array(),
      ),
    ),
    'views:enterprise_landingpage_blocks-rel_cta_footer' => array(
      'title' => '<none>',
      'class' => 'm-y-1',
      'cta' => array(
        'list_visibility' => 1,
        'selectors' => array(
          0 => 'cta_footer',
        ),
        'categories' => array(),
        'data' => array(),
      ),
    ),
  );

  return $settings;
}

/**
 * Implements hook_enterprise_config_apps_structures()
 *
 * Provides blocks config data
 * @return array
 */
function enterprise_conversion_config_enterprise_apps_config_info() {
  $structures = array();
  $structures['enterprise_conversion'] = array(
    'title' => t('Landing pages'),
  );

  $visibility_presets = array(
    'enterprise_landingpage_content_type' => array(
      'title' => t('Show on landing pages'),
      'node_type' => array(
        'types' => array(
          'enterprise_landingpage',
        ),
      )
    ),
    'enterprise_thankyou_content_type' => array(
      'title' => t('Show on thank you pages'),
      'node_type' => array(
        'types' => array(
          'enterprise_thankyou',
        ),
      )
    ),
    'exclude_front' => array(
      'title' => t('Exclude from front page'),
      'path' => array(
        'pages' => array(
          '<front>',
        ),
        'visibility' => 0,
      )
    ),
    'exclude_landingpage' => array(
      'title' => t('Exclude from landing pages'),
      'path' => array(
        'pages' => array(
          'offer/*',
        ),
        'visibility' => 0,
      )
    ),
    'exclude_thankyou' => array(
      'title' => t('Exclude from thank you pages'),
      'path' => array(
        'pages' => array(
          'thank-you/*',
        ),
        'visibility' => 0,
      )
    ),
  );

  $structures['enterprise_conversion']['blocks'] = array();

  $structures['enterprise_conversion']['blocks']['cta:sel_cta_sidebar'] = array(
    'description' => t('Selector for sidebar CTAs'),
    'default' => array(
      'regions' => array('sidebar_second'),
      'visibility_presets' => array(
        'exclude_front',
        'exclude_landingpage',
        'exclude_thankyou',
      ),
      'weight' => 0,
    ),
    'visibility_presets' => $visibility_presets,
  );
  $structures['enterprise_conversion']['blocks']['cta:sel_cta_footer'] = array(
    'description' => t('Selector for footer CTAs'),
    'default' => array(
      'regions' => array('content'),
      'visibility_presets' => array(
        'exclude_front',
        'exclude_landingpage',
        'exclude_thankyou',
      ),
      'weight' => 0,
    ),
    'visibility_presets' => $visibility_presets,
  );


  $display_desc = array();
  if (module_exists('enterprise_blog')) {
    $view = views_get_view('enterprise_blog_blocks');
    if (!empty($view)) {
      foreach ($view->display AS $name => $display) {
        $display_desc['blog:' . $name] = isset($display->display_options['display_description']) ? $display->display_options['display_description'] : '';
      }
    }
    $structures['enterprise_conversion']['blocks']['views:enterprise_blog_blocks-rel'] = array(
      'description' => $display_desc['blog:rel'],
      'default' => array(
        'visibility_presets' => array('enterprise_thankyou_content_type'),
      ),
      'visibility_presets' => $visibility_presets,
    );
  }

  return $structures;
}

/**
 * Implements hook_styler().
 *
 * Tell styler module what styles this module provides.
 */
function enterprise_conversion_config_styler_style() {
  $styles = array();

  $styles['ctas'] = array(
    '#title' => t('Calls to Action'),
    '#description' => t('Various templates for marking up CTAs.'),
  );

  $styles['ctas']['tags'] = array(
    '#title' => t('CTA tags'),
    '#description' => check_plain(t('Use the button classes on an <div>, <a>, <button>, or <input> element.')),
    'element' => array(
      '#tag' => 'markup',
      '#value' => '<a class="cta cta-default" href="#" role="button">Link</a>
<div class="cta cta-default" href="#" role="button">Div</div>
<button class="cta cta-default" type="submit">Button</button>
<input class="cta cta-default" type="button" value="Input">
<input class="cta cta-default" type="submit" value="Submit">',
    ),
  );

  $styles['ctas']['options'] = array(
    '#title' => t('Options'),
    '#description' => t('Use any of the available CTA classes to quickly create a styled CTA.'),
  );
  $styles['ctas']['options']['default'] = array(
    '#tag' => 'markup',
    '#value' => '<a href="#" class="cta cta-default">Default</a>
<a href="#" class="cta cta-primary">Primary</a>
<a href="#" class="cta cta-secondary">Secondary</a>
<a href="#" class="cta cta-accent">Accent</a>
<a href="#" class="cta cta-link">Link</a>',
  );


  // Buttons
  $styles['ctas']['button-group'] = array(
    '#title' => t('Button Groups'),
    '#description' => t('Extend buttons by adding text or icons before, after, or on both sides of any text-based button group body. Icons can be generated using the <code>&lt;i&gt;</code> tag and using the class attribute to specify the icon.'),
    'element' => array(
      '#tag' => 'markup',
      '#value_replace_eol' => 1,
      '#value' => '<a href="#" class="cta cta-default btn-group">
  <span class="btn-group-addon"><i class="icon glyphicon glyphicon-download"></i></span>
  <span class="btn-group-body">Download Now</span>
</a>

<a href="#" class="cta cta-primary btn-group">
  <span class="btn-group-body">Download Now</span>
  <span class="btn-group-addon"><i class="icon glyphicon glyphicon-ok-sign"></i></span>
</a>

<a href="#" class="cta cta-accent btn-group">
  <span class="btn-group-addon"><i class="icon glyphicon glyphicon-star"></i></span>
  <span class="btn-group-body">Download Now</span>
  <span class="btn-group-addon cta-default"><i class="icon glyphicon glyphicon-download"></i></span>
</a>
',
    ),
  );

  // Sidebar
  $styles['ctas']['panel'] = array(
    '#title' => t('Panels'),
    '#description' => t('The cta-panel class makes cta-header, cta-body and cta-footer full width to allow content and background colors to go full width.'),
    'element' => array(
      '#tag' => 'markup',
      '#value' => '
<div class="row">
  <div class="col-sm-6">
    Example 1:<br />
    <a href="#">
      <div class="cta cta-panel cta-default cta-outline-none cta-block">
        <div class="cta-heading cta-primary">
          <h3 class="cta-title">Call to Action Heading</h3>
        </div>
          <p class="m-t-1 m-b-1">
          Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.
          </p>

          <div class="cta cta-accent btn-group btn-block">
            <span class="btn-group-body">Download Now</span>
            <span class="btn-group-addon"><i class="icon glyphicon glyphicon-ok-sign"></i></span>
          </div>
      </div>
    </a>
  </div>
  <div class="col-sm-6">
    Example 2:<br />
    <a href="#">
      <div class="cta cta-panel cta-default cta-block">
        <div class="cta-heading cta-primary">
          <h3 class="cta-title text-left">Call to Action Heading</h3>
        </div>
        <div class="cta-body">
          <img src="http://placehold.it/120x150" class="pull-left" />
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>
        </div>
        <div class="cta-footer">
          <div class="cta cta-accent btn-group">
            <span class="btn-group-body">Download Now</span>
            <span class="btn-group-addon"><i class="icon glyphicon glyphicon-ok-sign"></i></span>
          </div>
        </div>
      </div>
    </a>
  </div>
</div>',
      '#value_highlight' => 'Example 1:
<div class="cta cta-default cta-block">
  <h3 class="cta-heading text-primary">Call to Action Heading</h3>
  <p>...</p>
  <button class="btn btn-cta btn-group">
    <span class="btn-group-body">Download Now</span>
    <span class="btn-group-addon"><i class="icon glyphicon glyphicon-download"></i></span>
  </button>
</div>

Example 2:
<div class="cta cta-primary">
  <h3 class="cta-heading text-left">Call to Action Heading</h3>
  <div class="row">
    <div class="col-lg-5 col-sm-12 col-xs-5">
      <img src="http://placehold.it/120x150"  style="max-height: 180px;"/>
    </div>
    <div class="col-lg-7 col-sm-12 col-xs-7 text-left">
      <p>...</p>
      <button class="btn btn-cta-accent btn-block">Download Now</button>
    </div>
  </div>
</div>',
    ),
  );

  // Sidebar
  $styles['ctas']['sidebar'] = array(
    '#title' => t('Sidebars'),
    '#description' => t('To be displayed in narrow containers such as sidebars.'),
    'element' => array(
      '#tag' => 'markup',
      '#value' => '
<div class="row">
  <div class="col-sm-6">
    Example 1:<br />
    <a href="#">
      <div class="cta cta-default cta-block">
        <h3 class="cta-title text-primary">Call to Action Heading</h3>
        <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>
        <button class="btn btn-cta btn-group">
          <span class="btn-group-body">Download Now</span>
          <span class="btn-group-addon"><i class="icon glyphicon glyphicon-download"></i></span>
        </button>
      </div>
    </a>
  </div>
  <div class="col-sm-6">
    Example 2:<br />
    <a href="#">
      <div class="cta cta-primary cta-block">
        <div class="cta-heading">
          <h3 class="cta-title text-left">Call to Action Heading</h3>
        </div>
        <div class="cta-body row">
          <div class="col-lg-5 col-sm-12 col-xs-5">
            <img src="http://placehold.it/120x150" style="max-height: 180px;" />
          </div>
          <div class="col-lg-7 col-sm-12 col-xs-7 text-left">
            <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
            <button class="btn cta-accent btn-block">Download Now</button>
          </div>
        </div>
      </div>
    </a>
  </div>
</div>',
      '#value_highlight' => 'Example 1:
<div class="cta cta-default cta-block">
  <h3 class="cta-heading text-primary">Call to Action Heading</h3>
  <p>...</p>
  <button class="btn btn-cta btn-group">
    <span class="btn-group-body">Download Now</span>
    <span class="btn-group-addon"><i class="icon glyphicon glyphicon-download"></i></span>
  </button>
</div>

Example 2:
<div class="cta cta-primary cta-block">
  <div class="cta-heading">
    <h3 class="cta-title text-left">Call to Action Heading</h3>
  </div>
  <div class="cta-body row">
    <div class="col-lg-5 col-sm-12 col-xs-5">
      <img src="http://placehold.it/120x150" />
    </div>
    <div class="col-lg-7 col-sm-12 col-xs-7 text-left">
      <p>....</p>
      <button class="btn cta-accent btn-block">Download Now</button>
    </div>
  </div>
</div>',
    ),
  );

  // Footer
  $styles['ctas']['footer'] = array(
    '#title' => t('Footers'),
    '#description' => t('To be displayed in wide format such as in content section.'),
    'element' => array(
      '#tag' => 'markup',
      '#value' => '<div class="row margin-bottom">
  <div class="col-md-12">
    Example 1:<br />
    <div class="cta cta-default cta-block">
      <h3 class="cta-title text-primary">Call to Action Heading</h3>
      <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
      <button class="btn btn-cta btn-group center-block">
        <span class="btn-group-body">Download Now</span>
        <span class="btn-group-addon"><i class="icon glyphicon glyphicon-download"></i></span>
      </button>
    </div>
  </div>
  </div>
<div class="row margin-bottom">
<div class="col-md-12">
    Example 2:<br />
    <div class="cta cta-primary cta-block">
      <div class="row">
        <div class="col-md-2 col-xs-4">
          <img src="http://placehold.it/120x150" style="max-height: 120px;" />
        </div>
        <div class="col-md-10 col-xs-8 text-left">
          <h3 class="cta-title">Call to Action Heading</h3>
          <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
          <button class="btn cta-accent btn-group center-block">
            <span class="btn-group-body">Download Now</span>
            <span class="btn-group-addon"><i class="icon glyphicon glyphicon-download"></i></span>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>',
      '#value_highlight' => 'Example 1:
<div class="cta cta-default cta-block">
  <h3 class="cta-title text-primary">Call to Action Heading</h3>
  <p>...</p>
  <button class="btn btn-cta btn-group center-block">
    <span class="btn-group-body">Download Now</span>
    <span class="btn-group-addon"><i class="icon glyphicon glyphicon-download"></i></span>
  </button>
</div>

Example 2:
<div class="cta cta-primary cta-block">
  <div class="row">
    <div class="col-md-2 col-xs-4">
      <img src="http://placehold.it/120x150" style="max-height: 120px;" />
    </div>
    <div class="col-md-10 col-xs-8 text-left">
      <h3 class="cta-title">Call to Action Heading</h3>
      <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
      <button class="btn cta-accent btn-group center-block">
        <span class="btn-group-body">Download Now</span>
        <span class="btn-group-addon"><i class="icon glyphicon glyphicon-download"></i></span>
      </button>
    </div>
  </div>
</div>',
    ),
  );
  /*
    $styles['ctas']['rectangle'] = array(
      '#title' => t('Rectangles'),
      '#description' => t('Icons can be generated using the <code>&lt;i&gt;</code> tag and using the class attribute to specify the icon.'),
      'element' => array(
        '#tag' => 'markup',
        '#value' => '<div class="row">
    <div class="col-md-6">
      <a href="#">
      <div class="cta cta-rectangle">
        <h3>Build a Smarter Website</h3>
        <p>Eight essential steps to transform your site into an inbound marketing machine.</p>
        <button class="btn-cta btn-group pull-right">
          <span class="btn-verb">Get it now!</span>
          <span class="btn-icon"><i class="icon glyphicon glyphicon-download"></i></span>
        </button>
      </div>
      </a>
    </div>
    <div class="col-md-6">
      <a href="#">
      <div class="cta cta-rectangle cta-secondary">
        <h3>Build a Smarter Website</h3>
        <div class="col-md-5">
          <img src="http://placehold.it/120x150" />
        </div>
        <div class="col-md-7">
          <p>Eight essential steps to transform your site into an inbound marketing machine.</p>
          <button class="btn-cta btn-group">
            <span class="btn-verb">Get it now!</span>
            <span class="btn-icon"><i class="icon glyphicon glyphicon-download"></i></span>
          </button>
        </div>
      </div>
      </a>
    </div>
  </div>',
        '#value_highlight' => 'Example 1:
  <div class="cta cta-rectangle">
    <h3>Build a Smarter Website</h3>
    <p>...</p>
    <button class="btn-cta btn-group pull-right">
            <span class="btn-verb">Get it now!</span>
            <span class="btn-icon"><i class="icon glyphicon glyphicon-download"></i></span>
          </button>
  </div>

  Example 2:
  <div class="cta cta-rectangle cta-secondary">
    <h3>Build a Smarter Website</h3>
    <div class="col-md-5">
      <img src="..." />
    </div>
    <div class="col-md-7">
      <p>....</p>
      <button class="btn-cta btn-group">
        <span class="btn-verb">Get it now!</span>
        <span class="btn-icon"><i class="icon glyphicon glyphicon-download"></i></span>
      </button>
    </div>
  </div>',
      ),
    );
    */

  return $styles;
}
