<?php
/**
 * @file
 * Code for the SEO Tools feature.
 */

include_once('seotools.features.inc');

/**
 * Implements hook_permission().
 */
function seotools_permission() {
  return array(
    'administer seotools' => array(
      'title' => t('Administer SEO Tools'),
      'description' => t('Can configure SEO Tools settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function seotools_menu() {
  // Module settings.
  
  $items['admin/config/search/seotools'] = array(
    'title' => 'SEO Tools',
    'description' => 'Configuration settings for SEO Tools.',
    'page callback' => 'seotools_admin_settings',
    'page arguments' => array(5),
    'access arguments' => array('administer seotools'),
    'file' => 'seotools.admin.inc',
    'weight' => 2,
    'type' => MENU_NORMAL_ITEM,
    //'type' => MENU_CALLBACK,
  );
  $items['admin/config/search/seotools/setup'] = array(
    'title' => 'Setup wizard',
    'description' => 'Setup wizard to help you get started quickly.',
    'page callback' => 'seotools_admin_setup',
    'page arguments' => array(5),
    'access arguments' => array('administer seotools'),
    'file' => 'seotools.setup.inc',
    'weight' => 2,
    'type' => MENU_LOCAL_ACTION,
    //'type' => MENU_CALLBACK,
  );

  $items['seotools/util'] = array(
    'title' => t('Social media util'),
    'page callback' => 'seotools_util',
    'access arguments' => array('administer-site-configuration'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function seotools_util() {
	return 'OK';
}


/**
 * Help to make exporting features easier. Functions below will add metatag
 * settings to features when a content type or taxonomy is selected
 */
/**
 * Implements hook_features_pipe_COMPONENT_alter().
 */
function seotools_features_pipe_node_alter(&$pipe, $data, $export) {
  foreach ($data as $node_type) {
    //$pipe['variable'][] = "metatag_enable_node__{$node_type}";
    //$pipe['variable'][] = "xmlsitemap_settings_node__{$node_type}";
  }
}

/**
 * Implements hook_features_pipe_COMPONENT_alter().
 */
function seotools_features_pipe_taxonomy_alter(&$pipe, $data, $export) {
  foreach ($data as $vocabulary) {
    //$pipe['variable'][] = "seotools_taxonomy_term__{$vocabulary}";
  }
}
