<?php
/**
 * @file
 * Code for the Enterprise Demo feature.
 */

include_once 'enterprise_demo_config.features.inc';

function enterprise_demo_config_enterprise_apps_config_settings() {
  $settings = array(
    'enterprise_demo' => array(),
  );

  $entity_info = array();
  $entity_info['node:enterprise_blog'] = array(
    'field_instance' => array(
      'field_cta_category' => 1,
      'field_intel_event_col' => 1,
      'field_keywords' => 1,
      'field_page_attribute_col' => 1,
      'field_visitor_attribute_col' => 1,
    ),
    'field_group' => array(
      'group_rel_label' => 1,
      'group_rel_container' => 1,
      'group_rel_global' => 1,
    ),
  );

  $entity_info['node:enterprise_landingpage'] = array(
    'field_instance' => array(
      //'field_cta_category' => 1,
      'field_intel_event_col' => 1,
      'field_keywords' => 1,
      'field_page_attribute_col' => 1,
      'field_visitor_attribute_col' => 1,
    ),
  );

  $entity_info['node:enterprise_thankyou'] = array(
    'field_instance' => array(
      //'field_cta_category' => 1,
      'field_intel_event_col' => 1,
      'field_keywords' => 1,
      'field_page_attribute_col' => 1,
      'field_visitor_attribute_col' => 1,
    ),
  );

  $entity_info['node:page'] = array(
    'field_instance' => array(
      'field_cta_category' => 1,
      'field_intel_event_col' => 1,
      'field_keywords' => 1,
      'field_page_attribute_col' => 1,
      'field_visitor_attribute_col' => 1,
    ),
  );

  $entity_info['node:webform'] = array(
    'field_instance' => array(
      //'field_cta_category' => 1,
      'field_intel_event_col' => 1,
      'field_keywords' => 1,
      'field_page_attribute_col' => 1,
      'field_visitor_attribute_col' => 1,
    ),
  );

  $settings['enterprise_demo']['entity_info'] = $entity_info;

  $blocks = array();
  $blocks['search:form'] = array(
    'regions' => array(
      'footer',
    ),
    'title' => t('Search OE Pro'),
    'weight' => 0,
  );

  $blocks['widgets:s_twitter-user-timeline-widget'] = array(
    'regions' => array(
      'footer',
    ),
    'weight' => 1,
  );

  $blocks['widgets:s_facebook-like-box'] = array(
    'regions' => array(
      'footer',
    ),
    'weight' => 2,
  );

  $blocks['widgets:s_enterprise_social-follow'] = array(
    'title' => t('Follow us'),
    'regions' => array(
      'footer',
    ),
    'block_row' => array(
      'row' => 'row2',
      'row_class' => 'stacked',
    ),
    'weight' => 3,
  );

  $blocks['views:enterprise_blog_blocks-tags'] = array(
    'weight' => 1,
  );

  $blocks['views:enterprise_blog_blocks-archives'] = array(
    'weight' => 2,
  );

  $blocks['views:enterprise_blog_blocks-popular'] = array(
    'weight' => 6,
  );

  $blocks['cta:sel_cta_sidebar'] = array(
    'path' => array(
      'pages' => array(
        '<front>',
        'admin/*',
        'user',
        'user/*',
        'users/*',
        'offer/*',
        'thank-you/*',
        'services',
        'services/*',
        'about',
        'about/*',
        'team',
        'forum',
        'forum/*',
      ),
    ),
  );

  // add cta footer to blog content type
  $blocks['cta:sel_cta_footer'] = array(
    'node_type' => array(
      'types' => array(
        'enterprise_blog',
      ),
    ),
  );

  $settings['enterprise_demo']['blocks'] = &$blocks;


  $variables = array();

  $settings['enterprise_demo']['variables'] = &$variables;

  $variables['theme_bella_settings'] = variable_get('theme_bella_settings');
  $variables['theme_bella_settings'] = array(
    'default_logo' => 0,
    'logo_path' => 'profiles/openenterprise/images/openenterprise_logo.png',
    'navbar_header_display' => 'none',
    'navbar_class' => 'navbar-gray-lighter',
    'less' => array(
      'bella' => array(
        '@brand-primary' => '#288CD5',
        //'@brand-primary' => '#1A68AE',
        //'@brand-primary' => '#2C90D9',
        '@brand-secondary' => '#83B941',
        '@brand-accent' => '#FFA126',
        //'@brand-primary' => '#168FAE',
        //'@brand-secondary' => '#A1C851',
        //'@brand-accent' => '#F7941E',
      )
    )
  );

  $blocks['bean:brand_bar'] = array(
    'regions' => array(
      'brand_bar',
    ),
  );

  return $settings;
}

/**
 * Implements hook_uuid_entities_features_import_entity_alter();
 * @param $entity
 * @param $entity_type
 */
function enterprise_demo_config_uuid_entities_features_import_entity_alter(&$entity, $entity_type) {

  // replace webform block placeholder in brand_bar bean
  if ($entity->entity_type == 'bean') {
    // try to load contact us form to get id
    if ($entity->delta == 'brand_bar' && function_exists('entity_get_id_by_uuid')) {
      $uuid = 'cf3a4aa8-a24a-4bac-af77-76b77020fa1d';
      $ids = entity_get_id_by_uuid('node', array($uuid));
      if (!empty($ids)) {
        $id = $ids[$uuid];
        $entity->field_body[LANGUAGE_NONE][0]['value'] = str_replace('(ADD WEBFORM BLOCK HERE)', "[block:webform=client-block-$id]", $entity->field_body[LANGUAGE_NONE][0]['value']);
      }

    }
    watchdog('TEST edc', print_r($entity, 1));

  }
}

