<?php
/**
 * @file
 * Code for the Enterprise Demo feature.
 */

function enterprise_demo_menu() {
  $items = array();
  $items['enterprise_demo/init'] = array(
    'title' => 'Enterprise demo init',
    'page callback' => 'enterprise_demo_init_app',
    'access callback' => 'user_access',
    'access arguments' => array('admin intel'),
    'type' => MENU_CALLBACK,
  );
  $items['enterprise_demo/util'] = array(
    'title' => 'Enterprise demo util',
    'page callback' => 'enterprise_demo_util',
    'access callback' => 'user_access',
    'access arguments' => array('admin intel'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function enterprise_demo_util() {

  $settings = variable_get('enterprise_apps_profile_settings', array());

  dsm($settings);

  $var = variable_get('enterprise_demo_debug', array());

  dsm($var);

  return '';

  features_revert(array('enterprise_demo' => array('field_instance')));

  return '';

  enterprise_apps_config_app('enterprise_webform_content');

  return '';
}

/**
 * Implements hook_enterprise_apps_app_enabled()
 */
function enterprise_demo_enterprise_apps_app_enabled_x() {
  // get batch processing for init_app
  //$batch = enterprise_apps_install_demo_batch_settings(enterprise_demo_enterprise_apps_install_demo_info());
  //batch_set($batch);
  //batch_process('<front>');
}

function enterprise_demo_enterprise_apps_install_demo_info() {
  global $base_path;

  $settings = variable_get('enterprise_apps_profile_settings', array());

  $required_apps = array(
    'enterprise_intel',
    'enterprise_social',
    'enterprise_social_content',
    'enterprise_seo',
    'enterprise_user',
    'enterprise_user_content',
    'enterprise_comments',
    'enterprise_blog',
    'enterprise_blog_content',
    'enterprise_dashboard',
    'enterprise_thankyoupage',
    'enterprise_thankyoupage_content',
    'enterprise_webform',
    'enterprise_webform_content',
  );
  if (!empty($settings['demo']['mode'])
    && (($settings['demo']['mode'] == 'attract_convert') || $settings['demo']['mode'] == 'standard')) {
    $required_apps[] = 'enterprise_landingpage';
    $required_apps[] = 'enterprise_conversion';
    $required_apps[] = 'enterprise_conversion_content';
  }



  $info = array(
    'required_apps' => $required_apps,
  );

  return $info;
}