<?php
/**
 * @file
 * Code for the Enterprise Comments feature.
 */

include_once 'enterprise_comments.features.inc';

/**
 * Implements hook_enterprise_apps_app_enabled()
 */
function enterprise_comments_enterprise_apps_app_enabled() {
  // get batch processing for init_app
  enterprise_apps_config_app('enterprise_comments');
}

function enterprise_comments_enterprise_apps_config_settings() {
  $settings = array(
    'enterprise_comments' => array(
      'blocks' => array(),
    ),
  );

  $settings['enterprise_comments']['blocks'] = array(
    'disqus:disqus_comments' => array(
      'regions' => array(
        'content',
      ),
      'weight' => 20,
    ),
  );

  return $settings;
}

function enterprise_comments_menu() {
  $items = array();

  $items['admin/content/comment_disqus'] = array(
    'title' => 'Comments',
    'page callback' => 'enterprise_comment_content_admin_page',
    'access callback' => 'user_access',
    'access arguments' => array('administer disqus'),
    //'type' => MENU_CALLBACK,
  );
  return $items;
}

function enterprise_comment_content_admin_page() {
  $block = module_invoke('disqus', 'block_view', 'disqus_combination_widget');
  return render($block['content']);
}


