<?php
/**
 * @file
 * Code for the Enterprise Health Services Plastic Surgery module.
 */


/**
 * Implements hook_taxonomy_term_VOCABULARY_MACHINE_NAME_uri_alter()
 *
 */
function enterprise_hsps_taxonomy_term_gender_uri_alter(&$url, $term) {
  $url['path'] = 'rel-view/' . $url['path'];
}

/**
 * Implements hook_taxonomy_term_VOCABULARY_MACHINE_NAME_uri_alter()
 *
 */
function enterprise_hsps_taxonomy_term_age_uri_alter(&$url, $term) {
  $url['path'] = 'rel-view/' . $url['path'];
}

/**
 * Implements hook_taxonomy_term_VOCABULARY_MACHINE_NAME_uri_alter()
 *
 */
function enterprise_hsps_taxonomy_term_height_uri_alter(&$url, $term) {
  $url['path'] = 'rel-view/' . $url['path'];
}

/**
 * Implements hook_taxonomy_term_VOCABULARY_MACHINE_NAME_uri_alter()
 *
 */
function enterprise_hsps_taxonomy_term_weight_uri_alter(&$url, $term) {
  $url['path'] = 'rel-view/' . $url['path'];
}

/**
 * Implements hook_taxonomy_term_VOCABULARY_MACHINE_NAME_uri_alter()
 *
 */
function enterprise_hsps_taxonomy_term_ethnicity_uri_alter(&$url, $term) {
  $url['path'] = 'rel-view/' . $url['path'];
}