<?php

/**
 * @file
 * Implements the basic functionality required to create and display an entity.
 *
 * This example does not use the
 * @link http://drupal.org/project/entity Entity API module @endlink, which is
 * used by many entity implementations and is recommended by many.
 *
 * An example of use of creating and managing entities using the Entity API
 * module is provided in the
 * @link http://drupal.org/project/model Model Entity module @endlink.
 *
 * @todo: Reference the ronald_istos article series
 * @todo: Reference the Drupal module development book
 * @todo: Add a single field
 */

/**
 * @defgroup entity_example Example: Entity
 * @ingroup examples
 * @{
 * Example creating a core Entity API entity.
 *
 * Note that this example does not use or demonstrate the contrib Entity API,
 * which you can find here: http://drupal.org/project/entity
 */

/**
 * Implements hook_menu().
 */
function intel_contact_menu() {
  $items['admin/config/people/intel_contact'] = array(
    'title' => 'Intelligence contact',
    'description' => 'Configure settings for people managed by Intelligence.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('intel_contact_admin_settings_form'),
    'access arguments' => array('administer users'),
    'file' => 'intel_contact.admin.inc',
    'weight' => -10,
  );
  $items['admin/config/people/intel_contact/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  // This provides a place for Field API to hang its own
  // interface and has to be the same as what was defined
  // in basic_entity_info() above.
  $items['admin/people/intel_contact'] = array(
    'title' => 'Administer intel_contact entity type',
    'page callback' => 'intel_contact_list_entities',
    'access arguments' => array('administer intel_contact entities'),
  );

  // The page to view our entities - needs to follow what
  // is defined in basic_uri and will use load_basic to retrieve
  // the necessary entity info.
  $items['contact/%intel_contact'] = array(
    'title callback' => 'intel_contact_title',
    'title arguments' => array(1),
    'page callback' => 'intel_contact_view',
    'page arguments' => array(1),
    'access arguments' => array('view any intel_contact entity'),
  );

  // 'View' tab for an individual entity page.
  $items['contact/%intel_contact/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  // 'Edit' tab for an individual entity page.
  $items['contact/%intel_contact/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('intel_contact_form', 3),
    'access arguments' => array('edit any intel_contact entity'),
    'type' => MENU_LOCAL_TASK,
  );

  // Add example entities.
  $items['contact/add'] = array(
    'title' => 'Add an Entity Example Basic Entity',
    'page callback' => 'intel_contact_add',
    'access arguments' => array('create intel_contact entities'),
  );

  $items['intel_contact/util'] = array(
    'title' => 'Util',
    'page callback' => 'intel_contact_util',
    'access arguments' => array('create intel_contact entities'),
  );

  return $items;
}

/**
 * Implements hook_admin_paths()
 */
function intel_contact_admin_paths() {
  $paths = array(
    'contact/*' => 1,
  );
  return $paths;
}

function intel_contact_util() {
  $output = '';

  $entity_types = EntityType::loadAll();
dsm($entity_types);

  return '';

  $field = array(
    'field_name' => 'intel_visitor',
    'type' => 'entityreference',
    'cardinality' => FIELD_CARDINALITY_UNLIMITED,
    'settings' => array(
      'target_type' => 'intel_visitor',
      'target_bundles' => array('intel_visitor'),
    ),
  );
  field_create_field($field);
  $instance = array(
    'field_name' => 'Intelligence',
    'entity_type' => 'intel_contact',
    'bundle' => 'intel_contact',
    'label' => 'Intelligence',
    'widget' => array(
      'type' => 'options_select',
    ),
  );
  field_create_instance($instance);
}

/**
 * Implements hook_entity_info().
 *
 * This is the fundamental description of the entity.
 *
 * It provides a single entity with a single bundle and without revision
 * support.
 */
function intel_contact_entity_info() {
  $info['intel_contact'] = array(
    'label' => t('Intel contact'),
    'controller class' => 'EntityIntelContactController',
    'entity class' => 'IntelContactEntity',
    'base table' => 'intel_contact',
    'uri callback' => 'intel_contact_uri',
    'label callback' => 'intel_contact_label',
    'module' => 'intel_contact',
    'fieldable' => TRUE,

    // entity_keys tells the controller what database fields are used for key
    // functions. It is not required if we don't have bundles or revisions.
    // Here we do not support a revision, so that entity key is omitted.
    'entity keys' => array(
      'id' => 'eid' , // The 'id' (eid here) is the unique id.
    ),
    // FALSE disables caching. Caching functionality is handled by Drupal core.
    'static cache' => TRUE,
    'bundles' => array(
      'intel_contact' => array(
        'label' => t('Intel contact'),
        // 'admin' key is used by the Field UI to provide field and
        // display UI pages.
        'admin' => array(
          'path' => 'admin/config/people/intel_contact',
          'access arguments' => array('administer intel_contact entities'),
        ),
      ),
    ),
    'view modes' => array(
      'full' => array(
        'label' => t('Contact profile'),
        'custom settings' => FALSE,
      ),
      'token' => array(
        'label' => t('Tokens'),
        'custom settings' => FALSE,
      ),
    ),
  );

  if (module_exists('uuid')) {
    $info['intel_contact']['uuid'] = TRUE;
    $info['intel_contact']['entity keys']['uuid'] = 'uuid';
  }

  return $info;
}

/**
 * Implements hook_entity_property_info().
 *
 * Add entity metadata properties for contact primary fields and UUID
 * integration, if UUID is enabled.
 *
 * @see entity_metadata_entity_property_info()
 */
function intel_contact_entity_property_info() {
  $info['intel_contact']['properties']['name'] = array(
    'label' => t('Name'),
    'type' => 'text',
    'description' => t('Get primary e-mail of CRM Core Contact.'),
    //'getter callback' => 'crm_core_contact_get_primary_email_field_value',
    //'computed' => TRUE,
  );

  if (module_exists('uuid')) {
    $info['intel_contact']['properties']['uuid'] = array(
      'label' => t('UUID'),
      'type' => 'text',
      'description' => t('The universally unique ID.'),
      'schema field' => 'uuid',
    );
  }

  return $info;
}

/**
 * Implements hook_field_extra_fields().
 *
 * This exposes the "extra fields" (usually properties that can be configured
 * as if they were fields) of the entity as pseudo-fields
 * so that they get handled by the Entity and Field core functionality.
 * Node titles get treated in a similar manner.
 */
function intel_contact_field_extra_fields() {
  $form_elements = array();
  $display_elements = array();
  $form_elements['name'] = array(
    'label' => t('Name'),
    'description' => t('Item Description (an extra form field)'),
    'weight' => -5,
  );
  $display_elements['created'] = array(
    'label' => t('Creation date'),
    'description' => t('Creation date (an extra display field)'),
    'weight' => 0,
  );

  // Since we have only one bundle type, we'll just provide the extra_fields
  // for it here.
  $extra_fields['intel_contact']['intel_contact']['form'] = $form_elements;
  $extra_fields['intel_contact']['intel_contact']['display'] = $display_elements;

  return $extra_fields;
}





/**
 * Fetch a basic object.
 *
 * This function ends up being a shim between the menu system and
 * intel_contact_load_multiple().
 *
 * This function gets its name from the menu system's wildcard
 * naming conventions. For example, /path/%wildcard would end
 * up calling wildcard_load(%wildcard value). In our case defining
 * the path: examples/entity_example/basic/%intel_contact in
 * hook_menu() tells Drupal to call intel_contact_load().
 *
 * @param $eid
 *   Integer specifying the basic entity id.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   A fully-loaded $basic object or FALSE if it cannot be loaded.
 *
 * @see intel_contact_load_multiple()
 * @see entity_example_menu()
 */
function intel_contact_load($eid = NULL, $reset = FALSE) {
  $eids = (isset($eid) ? array($eid) : array());
  $basic = intel_contact_load_multiple($eids, array(), $reset);
  return $basic ? reset($basic) : FALSE;
}

/**
 * Loads multiple basic entities.
 *
 * We only need to pass this request along to entity_load(), which
 * will in turn call the load() method of our entity controller class.
 */
function intel_contact_load_multiple($eids = FALSE, $conditions = array(), $reset = FALSE) {
  return entity_load('intel_contact', $eids, $conditions, $reset);
}

/**
 * Implements the uri callback.
 */
function intel_contact_uri($entity) {
  return array(
    'path' => $entity->uri(),
  );
}

function intel_contact_label($entity) {
  return $entity->label();
}



/**
 * Basic information for the page.
 */
function intel_contact_info_page() {
  $content['preface'] = array(
    '#type' => 'item',
    '#markup' => t('The entity example provides a simple example entity.')
  );
  if (user_access('administer intel_contact entities')) {
    $content['preface']['#markup'] =  t('You can administer these and add fields and change the view !link.',
      array('!link' => l(t('here'), 'admin/structure/intel_contact/manage'))
    );
  }
  $content['table'] = intel_contact_list_entities();

  return $content;
}

/**
 * Implements hook_permission().
 */
function intel_contact_permission() {
  $permissions = array(
    'administer intel_contact entities' =>  array(
      'title' => t('Administer intel_contact entities'),
    ),
    'view any intel_contact entity' => array(
      'title' => t('View any Entity Example Basic entity'),
    ),
    'edit any intel_contact entity' => array(
      'title' => t('Edit any Entity Example Basic entity'),
    ),
    'create intel_contact entities' => array(
      'title' => t('Create Entity Example Basic Entities'),
    ),
  );
  return $permissions;
}

/**
 * Returns a render array with all intel_contact entities.
 *
 * In this basic example we know that there won't be many entities,
 * so we'll just load them all for display. See pager_example.module
 * to implement a pager. Most implementations would probably do this
 * with the contrib Entity API module, or a view using views module,
 * but we avoid using non-core features in the Examples project.
 *
 * @see pager_example.module
 */
function intel_contact_list_entities() {
  $content = array();
  // Load all of our entities.
  $entities = intel_contact_load_multiple();
  if (!empty($entities)) {
    foreach ( $entities as $entity ) {
      // Create tabular rows for our entities.
      $rows[] = array(
        'data' => array(
          'id' => $entity->eid,
          'item_description' => l($entity->item_description, 'examples/intel_contact/basic/' . $entity->eid),
          'bundle' => $entity->bundle_type,
        ),
      );
    }
    // Put our entities into a themed table. See theme_table() for details.
    $content['entity_table'] = array(
      '#theme' => 'table',
      '#rows' => $rows,
      '#header' => array(t('ID'), t('Item Description'), t('Bundle')),
    );
  }
  else {
    // There were no entities. Tell the user.
    $content[] = array(
      '#type' => 'item',
      '#markup' => t('No intel_contact entities currently exist.'),
    );
  }
  return $content;
}

/**
 * Callback for a page title when this entity is displayed.
 */
function intel_contact_title($entity) {
  dsm($entity);
  return t('Contact @label', array('@label' => $entity->label()));
}

/**
 * Menu callback to display an entity.
 *
 * As we load the entity for display, we're responsible for invoking a number
 * of hooks in their proper order.
 *
 * @see hook_entity_prepare_view()
 * @see hook_entity_view()
 * @see hook_entity_view_alter()
 */
function intel_contact_view($entity, $view_mode = 'tweaky') {
  // Our entity type, for convenience.
  $entity_type = 'intel_contact';
  // Start setting up the content.
  $entity->content = array(
    '#view_mode' => $view_mode,
  );
  // Build fields content - this is where the Field API really comes in to play.
  // The task has very little code here because it all gets taken care of by
  // field module.
  // field_attach_prepare_view() lets the fields load any data they need
  // before viewing.
  field_attach_prepare_view($entity_type, array($entity->eid => $entity),
    $view_mode);
  // We call entity_prepare_view() so it can invoke hook_entity_prepare_view()
  // for us.
  entity_prepare_view($entity_type, array($entity->eid => $entity));
  // Now field_attach_view() generates the content for the fields.
  $entity->content += field_attach_view($entity_type, $entity, $view_mode);

  // OK, Field API done, now we can set up some of our own data.
  $entity->content['created'] = array(
    '#type' => 'item',
    '#title' => t('Created date'),
    '#markup' => format_date($entity->created),
  );

  // Now to invoke some hooks. We need the language code for
  // hook_entity_view(), so let's get that.
  global $language;
  $langcode = $language->language;
  // And now invoke hook_entity_view().
  module_invoke_all('entity_view', $entity, $entity_type, $view_mode,
    $langcode);
  // Now invoke hook_entity_view_alter().
  drupal_alter(array('intel_contact_view', 'entity_view'),
    $entity->content, $entity_type);

  // And finally return the content.
  return $entity->content;
}

/**
 * Provides a wrapper on the edit form to add a new entity.
 */
function intel_contact_add() {
  // Create a basic entity structure to be used and passed to the validation
  // and submission functions.
  $entity = entity_get_controller('intel_contact')->create();
  return drupal_get_form('intel_contact_form', $entity);
}

/**
 * Form function to create an intel_contact entity.
 *
 * The pattern is:
 * - Set up the form for the data that is specific to your
 *   entity: the columns of your base table.
 * - Call on the Field API to pull in the form elements
 *   for fields attached to the entity.
 */
function intel_contact_form($form, &$form_state, $entity) {
  dsm($entity);
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#required' => TRUE,
    '#default_value' => $entity->name,
  );

  $form['entity'] = array(
    '#type' => 'value',
    '#value' => $entity,
  );

  field_attach_form('intel_contact', $entity, $form, $form_state);

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    '#weight' => 100,
  );
  $form['delete'] = array(
    '#type' => 'submit',
    '#value' => t('Delete'),
    '#submit' => array('intel_contact_edit_delete'),
    '#weight' => 200,
  );

  return $form;
}


/**
 * Validation handler for intel_contact_add_form form.
 * We pass things straight through to the Field API to handle validation
 * of the attached fields.
 */
function intel_contact_form_validate($form, &$form_state) {
  field_attach_form_validate('intel_contact', $form_state['values']['entity'], $form, $form_state);
}


/**
 * Form submit handler: submits basic_add_form information
 */
function intel_contact_form_submit($form, &$form_state) {
  $entity = $form_state['values']['entity'];
  $entity->name = $form_state['values']['name'];
  field_attach_submit('intel_contact', $entity, $form, $form_state);
  $entity = intel_contact_save($entity);
  $form_state['redirect'] = 'contact/' . $entity->eid;
}

/**
 * Form deletion handler.
 *
 * @todo: 'Are you sure?' message.
 */
function intel_contact_edit_delete( $form , &$form_state ) {
  $entity = $form_state['values']['basic_entity'];
  intel_contact_delete($entity);
  drupal_set_message(t('The entity %item_description (ID %id) has been deleted',
    array('%item_description' => $entity->item_description, '%id' => $entity->eid))
  );
  $form_state['redirect'] = 'examples/intel_contact';
}

/**
 * We save the entity by calling the controller.
 */
function intel_contact_save(&$entity) {
  return entity_get_controller('intel_contact')->save($entity);
}

/**
 * Use the controller to delete the entity.
 */
function intel_contact_delete($entity) {
  entity_get_controller('intel_contact')->delete($entity);
}

class IntelContactEntity extends Entity {
  public function label() {
    return $this->name;
  }
  public function uri() {
    return 'contact/' . $this->identifier();
  }
}

/**
 * EntityIntelContactControllerInterface definition.
 *
 * We create an interface here because anyone could come along and
 * use hook_entity_info_alter() to change our controller class.
 * We want to let them know what methods our class needs in order
 * to function with the rest of the module, so here's a handy list.
 *
 * @see hook_entity_info_alter()
 */

interface EntityIntelContactControllerInterface
  extends DrupalEntityControllerInterface {
  public function create();
  public function save($entity);
  public function delete($entity);
}

/**
 * EntityIntelContactController extends DrupalDefaultEntityController.
 *
 * Our subclass of DrupalDefaultEntityController lets us add a few
 * important create, update, and delete methods.
 */
class EntityIntelContactController
  extends EntityAPIControllerExportable
  implements EntityIntelContactControllerInterface {

  /**
   * Create and return a new intel_contact entity.
   */
  public function create(array $values = array()) {
    
    $schema = drupal_get_schema('intel_contact');
    foreach ($schema['fields'] AS $key => $field) {
      $values[$key] = isset($field['default']) ? $field['default'] : '';
    }    
    
    $entity = parent::create($values);
    return $entity;
  }
  /**
   * Saves the custom fields using drupal_write_record()
   */
  public function save($entity) {
    // If our entity has no eid, then we need to give it a
    // time of creation.
    if (empty($entity->eid)) {
      $entity->created = time();
    }
    // Invoke hook_entity_presave().
    module_invoke_all('entity_presave', $entity, 'intel_contact');
    // The 'primary_keys' argument determines whether this will be an insert
    // or an update. So if the entity already has an ID, we'll specify
    // eid as the key.
    $primary_keys = $entity->eid ? 'eid' : array();
    // Write out the entity record.
    drupal_write_record('intel_contact', $entity, $primary_keys);
    // We're going to invoke either hook_entity_update() or
    // hook_entity_insert(), depending on whether or not this is a
    // new entity. We'll just store the name of hook_entity_insert()
    // and change it if we need to.
    $invocation = 'entity_insert';
    // Now we need to either insert or update the fields which are
    // attached to this entity. We use the same primary_keys logic
    // to determine whether to update or insert, and which hook we
    // need to invoke.
    if (empty($primary_keys)) {
      field_attach_insert('intel_contact', $entity);
    }
    else {
      field_attach_update('intel_contact', $entity);
      $invocation = 'entity_update';
    }
    // Invoke either hook_entity_update() or hook_entity_insert().
    module_invoke_all($invocation, $entity, 'intel_contact');
    return $entity;
  }

  /**
   * Delete a single entity.
   *
   * Really a convenience function for delete_multiple().
   */
  public function delete($entity) {
    $this->delete_multiple(array($entity));
  }

  /**
   * Delete one or more intel_contact entities.
   *
   * Deletion is unfortunately not supported in the base
   * DrupalDefaultEntityController class.
   *
   * @param $eids
   *   An array of entity IDs or a single numeric ID.
   */
  public function delete_multiple($entities) {
    $eids = array();
    if (!empty($entities)) {
      $transaction = db_transaction();
      try {
        foreach ($entities as $entity) {
          // Invoke hook_entity_delete().
          module_invoke_all('entity_delete', $entity, 'intel_contact');
          field_attach_delete('intel_contact', $entity);
          $eids[] = $entity->eid;
        }
        db_delete('intel_contact')
          ->condition('eid', $eids, 'IN')
          ->execute();
      }
      catch (Exception $e) {
        $transaction->rollback();
        watchdog_exception('intel_contact', $e);
        throw $e;
      }
    }
  }
}

/**
 * @} End of "defgroup entity_example".
 */
