<?php
/**
 * @file
 * Code for the Enterprise Press feature.
 */

include_once 'enterprise_press.features.inc';

/**
 * Implements hook_ds_classes_alter().
 * Provide the necessary classes for press types.
 */
function enterprise_press_ds_classes_alter(&$classes, $name) {
  if ('ds_classes_regions' === $name) {
    $classes['style-press-full'] = t('Press: Full');
    $classes['style-press-teaser'] = t('Press: Teaser');
  }
}

function enterprise_press_enterprise_apps_config_info() {
  $config = array();
  $config['enterprise_press'] = array(
    'title' => t('Press releases'),
  );
  $visibility = array(
    'enterprise_press_view' => array(
      'title' => t('Show on press release listing pages'),
      'views' => array(
        'views' => array('enterprise_press:page'),
      ),
    ),
    'enterprise_press_content_type' => array(
      'title' => t('Show on press release pages'),
      'node_type' => array(
        'types' => array('enterprise_press_release'),
      )
    ),
  );
  $view = views_get_view('enterprise_press');
  $display_desc = array();
  foreach ($view->display AS $name => $display) {
    $display_desc[$name] = isset($display->display_options['display_description']) ? $display->display_options['display_description'] : '';
  }

  $config['enterprise_press']['blocks'] = array(
    // Blog categories block
    'views:enterprise_press-recent' => array(
      'description' => $display_desc['recent'],
      'default' => array(
        'regions' => array('sidebar_second'),
        'visibility_presets' => array('enterprise_press_content_type'),
        'weight' => 5,
      ),
      'visibility_presets' => $visibility,
    ),
    /**/
  );
  return $config;
}
