/**
 * @file
 * projectSlideshow.js
 *
 * Provides settings for Revolution/Owl slideshows.
 */
var Drupal = Drupal || {};
(function($, Drupal) {
  "use strict";
  Drupal.behaviors.projectRevolution = {
    attach: function(context, settings) {
      // Revolution Slider
      if ($(".slider-banner-container", context).length > 0) {
        $(".tp-bannertimer", context).show();
        $('body:not(.transparent-header) .slider-banner-container .slider-banner-fullscreen',context).show().revolution({
          delay: 8000,
          startwidth: 1140,
          startheight: 520,
          fullWidth: "off",
          fullScreen: "on",
          fullScreenOffsetContainer: ".header-container",
          fullScreenOffset: "0",
          navigationArrows: "solo",
          navigationStyle: "preview2",
          navigationHAlign: "center",
          navigationVAlign: "bottom",
          navigationHOffset: 0,
          navigationVOffset: 20,
          soloArrowLeftHalign: "left",
          soloArrowLeftValign: "center",
          soloArrowLeftHOffset: 0,
          soloArrowLeftVOffset: 0,
          soloArrowRightHalign: "right",
          soloArrowRightValign: "center",
          soloArrowRightHOffset: 0,
          soloArrowRightVOffset: 0,
          spinner: "spinner2",
          stopLoop: "off",
          stopAfterLoops: -1,
          stopAtSlide: -1,
          onHoverStop: "off",
          shuffle: "off",
          hideTimerBar: "off",
          autoHeight: "off",
          forceFullWidth: "off",
          hideThumbsOnMobile: "off",
          hideNavDelayOnMobile: 1500,
          hideBulletsOnMobile: "off",
          hideArrowsOnMobile: "off",
          hideThumbsUnderResolution: 0,
          hideSliderAtLimit: 0,
          hideCaptionAtLimit: 0,
          hideAllCaptionAtLilmit: 0,
          startWithSlide: 0
        });
        $('.transparent-header .slider-banner-container .slider-banner-fullscreen',context).show().revolution({
          delay: 8000,
          startwidth: 1140,
          startheight: 520,
          fullWidth: "off",
          fullScreen: "on",
          fullScreenOffsetContainer: ".header-top",
          fullScreenOffset: "",
          navigationArrows: "solo",
          navigationStyle: "preview2",
          navigationHAlign: "center",
          navigationVAlign: "bottom",
          navigationHOffset: 0,
          navigationVOffset: 20,
          soloArrowLeftHalign: "left",
          soloArrowLeftValign: "center",
          soloArrowLeftHOffset: 0,
          soloArrowLeftVOffset: 0,
          soloArrowRightHalign: "right",
          soloArrowRightValign: "center",
          soloArrowRightHOffset: 0,
          soloArrowRightVOffset: 0,
          spinner: "spinner2",
          stopLoop: "off",
          stopAfterLoops: -1,
          stopAtSlide: -1,
          onHoverStop: "off",
          shuffle: "off",
          hideTimerBar: "off",
          autoHeight: "off",
          forceFullWidth: "off",
          hideThumbsOnMobile: "off",
          hideNavDelayOnMobile: 1500,
          hideBulletsOnMobile: "off",
          hideArrowsOnMobile: "off",
          hideThumbsUnderResolution: 0,
          hideSliderAtLimit: 0,
          hideCaptionAtLimit: 0,
          hideAllCaptionAtLilmit: 0,
          startWithSlide: 0
        });
        $('.slider-banner-container .slider-banner-fullwidth', context).show().revolution({
            delay: 8000,
            startwidth: 1140,
            startheight: 450,
            navigationArrows: "solo",
            navigationStyle: "preview2",
            navigationHAlign: "center",
            navigationVAlign: "bottom",
            navigationHOffset: 0,
            navigationVOffset: 20,
            soloArrowLeftHalign: "left",
            soloArrowLeftValign: "center",
            soloArrowLeftHOffset: 0,
            soloArrowLeftVOffset: 0,
            soloArrowRightHalign: "right",
            soloArrowRightValign: "center",
            soloArrowRightHOffset: 0,
            soloArrowRightVOffset: 0,
            fullWidth: "on",
            spinner: "spinner2",
            stopLoop: "off",
            stopAfterLoops: -1,
            stopAtSlide: -1,
            onHoverStop: "off",
            shuffle: "off",
            autoHeight: "off",
            forceFullWidth: "off",
            hideThumbsOnMobile: "off",
            hideNavDelayOnMobile: 1500,
            hideBulletsOnMobile: "off",
            hideArrowsOnMobile: "off",
            hideThumbsUnderResolution: 0,
            hideSliderAtLimit: 0,
            hideCaptionAtLimit: 0,
            hideAllCaptionAtLilmit: 0,
            startWithSlide: 0
          });
        $('.slider-banner-container .slider-banner-fullwidth-big-height',context).show().revolution({
          delay: 8000,
          startwidth: 1140,
          startheight: 650,
          navigationArrows: "solo",
          navigationStyle: "preview2",
          navigationHAlign: "center",
          navigationVAlign: "bottom",
          navigationHOffset: 0,
          navigationVOffset: 20,
          soloArrowLeftHalign: "left",
          soloArrowLeftValign: "center",
          soloArrowLeftHOffset: 0,
          soloArrowLeftVOffset: 0,
          soloArrowRightHalign: "right",
          soloArrowRightValign: "center",
          soloArrowRightHOffset: 0,
          soloArrowRightVOffset: 0,
          fullWidth: "on",
          spinner: "spinner2",
          stopLoop: "off",
          stopAfterLoops: -1,
          stopAtSlide: -1,
          onHoverStop: "off",
          shuffle: "off",
          autoHeight: "off",
          forceFullWidth: "off",
          hideThumbsOnMobile: "off",
          hideNavDelayOnMobile: 1500,
          hideBulletsOnMobile: "off",
          hideArrowsOnMobile: "off",
          hideThumbsUnderResolution: 0,
          hideSliderAtLimit: 0,
          hideCaptionAtLimit: 0,
          hideAllCaptionAtLilmit: 0,
          startWithSlide: 0
        });
        $('.banner:not(.dark-bg) .slider-banner-container .slider-banner-boxedwidth',context).show().revolution({
          delay: 8000,
          startwidth: 1140,
          startheight: 450,
          navigationArrows: "solo",
          navigationStyle: "preview2",
          navigationHAlign: "center",
          navigationVAlign: "bottom",
          navigationHOffset: 0,
          navigationVOffset: 20,
          soloArrowLeftHalign: "left",
          soloArrowLeftValign: "center",
          soloArrowLeftHOffset: 0,
          soloArrowLeftVOffset: 0,
          soloArrowRightHalign: "right",
          soloArrowRightValign: "center",
          soloArrowRightHOffset: 0,
          soloArrowRightVOffset: 0,
          fullWidth: "off",
          spinner: "spinner2",
          shadow: 1,
          stopLoop: "off",
          stopAfterLoops: -1,
          stopAtSlide: -1,
          onHoverStop: "off",
          shuffle: "off",
          autoHeight: "off",
          forceFullWidth: "off",
          hideThumbsOnMobile: "off",
          hideNavDelayOnMobile: 1500,
          hideBulletsOnMobile: "off",
          hideArrowsOnMobile: "off",
          hideThumbsUnderResolution: 0,
          hideSliderAtLimit: 0,
          hideCaptionAtLimit: 0,
          hideAllCaptionAtLilmit: 0,
          startWithSlide: 0
        });
        $('.banner.dark-bg .slider-banner-container .slider-banner-boxedwidth',context).show().revolution({
          delay: 8000,
          startwidth: 1140,
          startheight: 450,
          navigationArrows: "solo",
          navigationStyle: "preview2",
          navigationHAlign: "center",
          navigationVAlign: "bottom",
          navigationHOffset: 0,
          navigationVOffset: 20,
          soloArrowLeftHalign: "left",
          soloArrowLeftValign: "center",
          soloArrowLeftHOffset: 0,
          soloArrowLeftVOffset: 0,
          soloArrowRightHalign: "right",
          soloArrowRightValign: "center",
          soloArrowRightHOffset: 0,
          soloArrowRightVOffset: 0,
          fullWidth: "off",
          spinner: "spinner2",
          shadow: 3,
          stopLoop: "off",
          stopAfterLoops: -1,
          stopAtSlide: -1,
          onHoverStop: "off",
          shuffle: "off",
          autoHeight: "off",
          forceFullWidth: "off",
          hideThumbsOnMobile: "off",
          hideNavDelayOnMobile: 1500,
          hideBulletsOnMobile: "off",
          hideArrowsOnMobile: "off",
          hideThumbsUnderResolution: 0,
          hideSliderAtLimit: 0,
          hideCaptionAtLimit: 0,
          hideAllCaptionAtLilmit: 0,
          startWithSlide: 0
        });
        $('.slider-banner-container .slider-banner-boxedwidth-no-shadow',context).show().revolution({
          delay: 8000,
          startwidth: 1140,
          startheight: 450,
          navigationArrows: "solo",
          navigationStyle: "preview2",
          navigationHAlign: "center",
          navigationVAlign: "bottom",
          navigationHOffset: 0,
          navigationVOffset: 20,
          soloArrowLeftHalign: "left",
          soloArrowLeftValign: "center",
          soloArrowLeftHOffset: 0,
          soloArrowLeftVOffset: 0,
          soloArrowRightHalign: "right",
          soloArrowRightValign: "center",
          soloArrowRightHOffset: 0,
          soloArrowRightVOffset: 0,
          fullWidth: "off",
          spinner: "spinner2",
          shadow: 0,
          stopLoop: "off",
          stopAfterLoops: -1,
          stopAtSlide: -1,
          onHoverStop: "off",
          shuffle: "off",
          autoHeight: "off",
          forceFullWidth: "off",
          hideThumbsOnMobile: "off",
          hideNavDelayOnMobile: 1500,
          hideBulletsOnMobile: "off",
          hideArrowsOnMobile: "off",
          hideThumbsUnderResolution: 0,
          hideSliderAtLimit: 0,
          hideCaptionAtLimit: 0,
          hideAllCaptionAtLilmit: 0,
          startWithSlide: 0
        });
        $('.banner:not(.dark-bg) .slider-banner-container .slider-banner-boxedwidth-stopped',context).show().revolution({
          delay: 8000,
          startwidth: 1140,
          startheight: 450,
          navigationArrows: "solo",
          navigationStyle: "preview2",
          navigationHAlign: "center",
          navigationVAlign: "bottom",
          navigationHOffset: 0,
          navigationVOffset: 20,
          soloArrowLeftHalign: "left",
          soloArrowLeftValign: "center",
          soloArrowLeftHOffset: 0,
          soloArrowLeftVOffset: 0,
          soloArrowRightHalign: "right",
          soloArrowRightValign: "center",
          soloArrowRightHOffset: 0,
          soloArrowRightVOffset: 0,
          fullWidth: "off",
          spinner: "spinner2",
          shadow: 1,
          stopLoop: "off",
          stopAfterLoops: 0,
          stopAtSlide: 1,
          onHoverStop: "off",
          shuffle: "off",
          autoHeight: "off",
          forceFullWidth: "off",
          hideThumbsOnMobile: "off",
          hideNavDelayOnMobile: 1500,
          hideBulletsOnMobile: "off",
          hideArrowsOnMobile: "off",
          hideThumbsUnderResolution: 0,
          hideSliderAtLimit: 0,
          hideCaptionAtLimit: 0,
          hideAllCaptionAtLilmit: 0,
          startWithSlide: 0
        });
        $('.banner.dark-bg .slider-banner-container .slider-banner-boxedwidth-stopped',context).show().revolution({
          delay: 8000,
          startwidth: 1140,
          startheight: 450,
          navigationArrows: "solo",
          navigationStyle: "preview2",
          navigationHAlign: "center",
          navigationVAlign: "bottom",
          navigationHOffset: 0,
          navigationVOffset: 20,
          soloArrowLeftHalign: "left",
          soloArrowLeftValign: "center",
          soloArrowLeftHOffset: 0,
          soloArrowLeftVOffset: 0,
          soloArrowRightHalign: "right",
          soloArrowRightValign: "center",
          soloArrowRightHOffset: 0,
          soloArrowRightVOffset: 0,
          fullWidth: "off",
          spinner: "spinner2",
          shadow: 3,
          stopLoop: "off",
          stopAfterLoops: 0,
          stopAtSlide: 1,
          onHoverStop: "off",
          shuffle: "off",
          autoHeight: "off",
          forceFullWidth: "off",
          hideThumbsOnMobile: "off",
          hideNavDelayOnMobile: 1500,
          hideBulletsOnMobile: "off",
          hideArrowsOnMobile: "off",
          hideThumbsUnderResolution: 0,
          hideSliderAtLimit: 0,
          hideCaptionAtLimit: 0,
          hideAllCaptionAtLilmit: 0,
          startWithSlide: 0
        });
      }
      //Owl carousel
      //-----------------------------------------------
      if ($('.owl-carousel', context).length > 0) {
        $(".owl-carousel.carousel", context).owlCarousel({
          items: 4,
          pagination: false,
          navigation: true,
          navigationText: false
        });
        $(".owl-carousel.carousel-autoplay", context).owlCarousel({
          items: 4,
          autoPlay: 5000,
          pagination: false,
          navigation: true,
          navigationText: false
        });
        $(".owl-carousel.clients", context).owlCarousel({
          items: 6,
          autoPlay: true,
          pagination: false,
          itemsDesktopSmall: [992, 4],
          itemsTablet: [768, 4],
          itemsMobile: [479, 3]
        });
        $(".owl-carousel.content-slider", context).owlCarousel({
          singleItem: true,
          autoPlay: 5000,
          navigation: false,
          navigationText: false,
          pagination: false
        });
        $(".owl-carousel.content-slider-with-controls", context).owlCarousel({
          singleItem: true,
          autoPlay: false,
          navigation: true,
          pagination: true
        });
        $(".owl-carousel.content-slider-with-large-controls", context).owlCarousel({
          singleItem: true,
          autoPlay: false,
          navigation: true,
          pagination: true
        });
        $(".owl-carousel.content-slider-with-controls-autoplay", context)
          .owlCarousel({
            singleItem: true,
            autoPlay: 5000,
            navigation: true,
            pagination: true
          });
        $(".owl-carousel.content-slider-with-large-controls-autoplay",
          context).owlCarousel({
          singleItem: true,
          autoPlay: 5000,
          navigation: true,
          pagination: true
        });
        $(
          ".owl-carousel.content-slider-with-controls-autoplay-hover-stop",
          context).owlCarousel({
          singleItem: true,
          autoPlay: 5000,
          navigation: true,
          pagination: true,
          stopOnHover: true
        });
      }
    }
  };
})(jQuery, Drupal);
