<?php

/**
 * @file
 */



function enterprise_guide_page_build(&$page) {
  _enterprise_guide_add_js();
}




function _enterprise_guide_add_js() {
  drupal_add_js(libraries_get_path('guiders-js') . '/guiders.js');
  drupal_add_css(libraries_get_path('guiders-js') . '/guiders.css');
  drupal_add_library('system', 'jquery.cookie');
  drupal_add_js(drupal_get_path('module', 'enterprise_guide') . '/enterprise_guide.js');
  //drupal_add_js(drupal_get_path('module', 'enterprise_guide') . '/guides/change_site_title.js');
  drupal_add_js(drupal_get_path('module', 'enterprise_guide') . '/guides/edit_content.js');
}

/*
function enterprise_guide_js_alter(&$javascript) {
  dsm($javascript);
}
*/



