<?php
/**
 * @file
 * enterprise_press_content.features.uuid_entities.inc
 */

/**
 * Implements hook_uuid_default_entities().
 */
function enterprise_press_content_uuid_default_entities() {
  $entities = array();

  $entities['enterprise_press_content'][] = (object) array(
    '__metadata' => array(
      'type' => 'node',
      'uri' => 'node/4b505135-a1b2-469f-99c5-997251359b63',
      'cause' => FALSE,
    ),
    'body' => array(
      'und' => array(
        0 => array(
          'format' => 'full_html',
          'summary' => '',
          'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec egestas justo. Mauris lorem justo, pellentesque id feugiat ut, malesuada tristique eros. Nunc varius quis metus vel bibendum. Nunc leo orci, convallis vel metus ac, auctor auctor metus. Suspendisse rutrum, enim ut posuere dignissim, enim erat tincidunt sem, nec venenatis mauris nunc ut massa. Fusce volutpat mi et nisl volutpat, pharetra vehicula eros placerat. Vestibulum placerat volutpat pretium.</p>

<p>Duis a enim mauris. Maecenas tellus odio, egestas at rhoncus ut, pharetra vel neque. Nullam ultrices aliquam tellus sit amet luctus. Donec et nunc vitae elit varius varius. Sed gravida eros quis ligula pulvinar tristique. Aenean ultricies tortor quis est pharetra, vitae semper metus gravida. Curabitur porttitor lorem urna, sit amet consequat mi tristique ut. Aliquam dignissim turpis ac purus sodales condimentum. Morbi a ullamcorper nisi, id scelerisque justo. Pellentesque diam leo, tincidunt ut suscipit eu, interdum mattis neque. Quisque quis laoreet nulla, eu gravida nulla.</p>

<p>Cras sit amet blandit tellus. Curabitur tempor eget risus sit amet semper. Duis eget felis vitae ligula vestibulum dictum. Suspendisse vel risus magna. Pellentesque bibendum dui vitae nulla tristique, at ultrices massa pellentesque. Nunc tempus nisl vel urna sagittis, id feugiat justo venenatis. Etiam sem mi, pharetra sed est at, suscipit facilisis magna. Morbi ut velit eget ante dapibus imperdiet et sit amet est. Donec sagittis, nibh sit amet semper semper, mi turpis fermentum purus, non tincidunt lorem nibh sed massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed ornare tristique sodales. Suspendisse at nunc vitae neque elementum porttitor vitae sed velit. Nam nisi lectus, accumsan tristique rutrum vel, mollis at eros.</p>

<p>Quisque ac cursus justo. Nullam urna erat, tristique sed dictum eget, fermentum vitae enim. Nullam fringilla lectus vel urna blandit sollicitudin. Donec non eros sed enim iaculis rhoncus sit amet in mauris. Proin placerat lobortis metus ac luctus. Nunc malesuada dui pellentesque congue rhoncus. Sed eu elit hendrerit, molestie est non, egestas sapien. In venenatis venenatis magna, non vestibulum velit porta eget.</p>

<p>Nam id purus justo. Pellentesque libero sapien, blandit quis est at, pellentesque ultrices libero. Quisque at tortor odio. Morbi id molestie eros. Fusce sit amet congue elit. Suspendisse in odio at turpis ullamcorper pretium. Aliquam eu massa nunc. Donec porttitor ullamcorper nulla et commodo. Integer aliquet ornare sem quis laoreet. Morbi quam libero, semper in commodo id, cursus at justo. Nunc fermentum pulvinar pharetra. Pellentesque venenatis dapibus libero eget convallis. Donec sapien felis, dignissim sit amet tortor at, aliquet luctus enim.</p>
',
        ),
      ),
    ),
    'cid' => 0,
    'comment' => 1,
    'comment_count' => 0,
    'entity_type' => 'node',
    'field_press_pdf' => array(),
    'language' => 'und',
    'last_comment_name' => NULL,
    'last_comment_uid' => 1,
    'log' => '',
    'metatags' => array(),
    'promote' => 1,
    'slug' => 'levelten_creates_new_distribution_for_sil_international',
    'status' => 1,
    'sticky' => 0,
    'title' => 'LevelTen Creates New Distribution for SIL International',
    'tnid' => 0,
    'translate' => 0,
    'type' => 'enterprise_press_release',
    'uid' => 1,
    'url_alias' => array(
      0 => array(
        'alias' => 'company/press-releases/levelten-creates-new-distribution-sil-international',
        'language' => 'und',
      ),
    ),
    'uuid' => '4b505135-a1b2-469f-99c5-997251359b63',
  );

  return $entities;
}
