<?php
/**
 * @file
 * Code for the Enterprise Theme feature.
 */

include_once 'enterprise_theme.features.inc';


/**
 * Implements hook_less_variables_alter().
 */
function enterprise_theme_less_variables_alter(&$less_variables, $system_name) {
  // Grab the color palette saved by the color module.
  $color_pallete = variable_get('less_colors', FALSE);
  
  // If the color palette hasn't been saved yet, use the default.
  if (empty($color_pallete)) {
    $color_pallete = array(
      'brand-primary' => '#EA9B3E',   // Orange
      'brand-secondary' => '#F5F5F5', // Gray
      'brand-accent' => '#FFFFF',     // White
      'brand-accent2' => '#EA9B3E',   // Orange
      'brand-accent3' => '#EA9B3E',   // Orange
    );
  }
  // Generate variables with color values.
  foreach ($color_pallete as $key => $value) {
    $color_pallete['@'.$key] = $color_pallete[$key];
    unset($color_pallete[$key]);
  }

  $less_variables = $color_pallete;
  return $color_pallete;
}

/**
 * Implements hook_page_alter().
 */
function enterprise_theme_page_alter(&$page) {
  // Only run on admin pages.
  $module_path = drupal_get_path('module', 'enterprise_theme');
  if (path_is_admin(current_path())) {
    drupal_add_css($module_path . '/enterprise_theme.admin.css');
  }
}
