<?php
/**
 * @file
 * Code for the Enterprise Theme feature.
 */

include_once 'enterprise_theme.features.inc';


/**
 * Implements hook_less_variables_alter().
 */
function enterprise_theme_less_variables_alter(&$less_variables, $system_name) {
  // Grab the color palette provided by the theme.
  $theme_name = variable_get('theme_default', NULL);
  $theme_settings = 'theme_'.$theme_name.'_settings';
  $settings = variable_get($theme_settings, NULL);

  // Reassign variables.
  foreach ($settings as $key => $value) {
    switch ($key) {
      case 'brand_color_1':
        $less_variables['@brand-primary'] = $value;
        break;
      case 'brand_color_2':
        $less_variables['@brand-secondary'] = $value;
        break;
      case 'brand_color_3':
        $less_variables['@brand-accent'] = $value;
        break;
      case 'brand_color_4':
        $less_variables['@brand-accent-2'] = $value;
        break;
      case 'brand_color_5':
        $less_variables['@brand-accent-3'] = $value;
        break;
    }
  }

}

/**
 * Implements hook_page_alter().
 */
function enterprise_theme_page_alter(&$page) {
  // Only run on admin pages.
  $module_path = drupal_get_path('module', 'enterprise_theme');
  if (path_is_admin(current_path())) {
    drupal_add_css($module_path . '/enterprise_theme.admin.css');
  }
}

/**
 * Implementation of hook_theme().
 */
function enterprise_theme_theme($existing, $type, $theme, $path) {
  return array(
    'pictaculous_info' => array(
      'variables' => array('object' => NULL),
      'template' => 'templates/pictaculous-info',
    ),
    'pictaculous_kuler' => array(
      'variables' => array('object' => NULL),
      'template' => 'templates/pictaculous-kuler',
    ),
    'pictaculous_colour' => array(
      'variables' => array('object' => NULL),
      'template' => 'templates/pictaculous-colour',
    ),
    'pictaculous_color_palette' => array(
      'variables' => array('colors' => NULL),
      'template' => 'templates/pictaculous-color-palette',
    ),
  );
}
