<?php
/**
 * @file
 * Code for the Enterprise Video feature.
 */

include_once 'enterprise_video.features.inc';

/**
 * Implements hook_enterprise_apps_on_enable()
 */
function xenterprise_video_enterprise_apps_app_enabled() {
  enterprise_apps_config_app('enterprise_video');
}

function enterprise_video_enterprise_apps_config_settings() {
  $settings = array(
    'enterprise_video' => array(),
  );

  $settings['enterprise_video']['options'] = array(
    'app_slug' => 'video',
    'section_path' => 'cool-videos',
    'section_path_node' => 'cool-video',
    'multi_author' => FALSE,  // FALSE or number for path slug order
    'taxonomy_categories' => 'blog_categories',
    'taxonomy_tags' => 'blog_tags',
  );

  $variables = array();
  $variables['disqus_nodetypes'] = array(
    'enterprise_video' => 'enterprise_video',
  );

  $settings['enterprise_video']['variables'] = $variables;

  return $settings;
}


/**
 * Implements hook_enterprise_apps_config_info()
 * @return array
 */
function enterprise_video_enterprise_apps_config_info() {
  $config = array();
  $config['enterprise_video'] = array(
    'title' => t('Video'),
  );

  // blocks config
  $visibility = array(
    'enterprise_video_view' => array(
      'title' => t('Show on video listing pages'),
      'views' => array(
        'views' => array(
          'enterprise_video:page',
          'enterprise_video:embedded_page',
        ),
      ),
    ),
    'enterprise_video_content_type' => array(
      'title' => t('Show on video pages'),
      'node_type' => array(
        'types' => array('enterprise_video'),
      )
    ),
  );
  $view = views_get_view('enterprise_video');
  $display_desc = array();
  if (!empty($view)) {
    foreach ($view->display AS $name => $display) {
      $display_desc[$name] = isset($display->display_options['display_description']) ? $display->display_options['display_description'] : '';
    }
  }

  $config['enterprise_video']['blocks'] = array(
    // Blog categories block
    'views:enterprise_video-categories_block' => array(
      'description' => $display_desc['categories'],
      'default' => array(
        'regions' => array('sidebar_second'),
        'visibility_presets' => array('enterprise_video_view', 'enterprise_video_content_type'),
        'weight' => -5,
      ),
      'visibility_presets' => $visibility,
    ),
    'views:enterprise_video-tags_block' => array(
      'description' => $display_desc['tags'],
      'default' => array(
        'regions' => array('sidebar_second'),
        'visibility_presets' => array('enterprise_video_view', 'enterprise_video_content_type'),
        'weight' => -4,
      ),
      'visibility_presets' => $visibility,
    ),
    'views:enterprise_video-recent_block' => array(
      'description' => $display_desc['recent'],
      'default' => array(
        'regions' => array('sidebar_second'),
        'visibility_presets' => array('enterprise_video_view', 'enterprise_video_content_type'),
        'weight' => 5,
      ),
      'visibility_presets' => $visibility,
    ),
    /*
    'views:enterprise_video_blocks-popular' => array(
      'description' => $display_desc['popular'],
      'default' => array(
        'regions' => array('sidebar_second'),
        'visibility_presets' => array('enterprise_video_view', 'enterprise_video_content_type'),
        'weight' => 6,
      ),
      'visibility_presets' => $visibility,
    ),
    'views:enterprise_blog_blocks-related' => array(
      'description' => $display_desc['related'],
      'default' => array(
        'regions' => array('content'),
        'visibility_presets' => array('enterprise_blog_content_type'),
        'weight' => 5,
      ),
      'visibility_presets' => $visibility,
    ),
    */
    /**/
  );
  return $config;
}