<?php
/**
 * @file
 * Code for the Enterprise landing pages feature.
 */

include_once 'enterprise_conversion_config.features.inc';

/**
 * Implements hook_enterprise_apps_app_enabled()
 */
function enterprise_conversion_config_enterprise_apps_app_enabled() {
  enterprise_apps_config_app('enterprise_conversion');
}

function enterprise_conversion_config_enterprise_apps_config_settings() {
  $settings = array(
    'enterprise_conversion' => array(),
  );

  $settings['enterprise_conversion']['blocks'] = array(
    // add forms selector to landing page
    'cta:sel_cta_forms' => array(
      'regions' => array(
        'sidebar_second',
      ),
      'node_type' => array(
        'types' => array(
          'enterprise_landingpage',
        ),
      ),
      'weight' => 0,
      'class' => 'm-t-1 m-b-1',
    ),
    'cta:sel_cta_sidebar' => array(
      'path' => array(
        'pages' => array(
          'admin/*',
        ),
        'visibility' => 0,
      ),
      'weight' => 0,
    ),
    'cta:sel_cta_footer' => array(
      'path' => array(
        'pages' => array(
          'admin/*',
        ),
        'visibility' => 0,
      ),
      'weight' => 10,
    ),
    'views:enterprise_landingpage_blocks-rel_cta_sidebar' => array(
      'title' => '<none>',
      'cta' => array(
        'list_visibility' => 1,
        'selectors' => array(
          0 => 'cta_sidebar',
        ),
        'categories' => array(),
        'data' => array(),
      ),
    ),
    'views:enterprise_landingpage_blocks-rel_cta_footer' => array(
      'title' => '<none>',
      'cta' => array(
        'list_visibility' => 1,
        'selectors' => array(
          0 => 'cta_footer',
        ),
        'categories' => array(),
        'data' => array(),
      ),
    ),
  );

  return $settings;
}

/**
 * Implements hook_enterprise_config_apps_structures()
 *
 * Provides blocks config data
 * @return array
 */
function enterprise_conversion_config_enterprise_apps_config_info() {
  $structures = array();
  $structures['enterprise_conversion'] = array(
    'title' => t('Landing pages'),
  );

  $visibility_presets = array(
    'enterprise_landingpage_content_type' => array(
      'title' => t('Show on landing pages'),
      'node_type' => array(
        'types' => array(
          'enterprise_landingpage',
        ),
      )
    ),
    'enterprise_thankyou_content_type' => array(
      'title' => t('Show on thank you pages'),
      'node_type' => array(
        'types' => array(
          'enterprise_thankyou',
        ),
      )
    ),
    'exclude_front' => array(
      'title' => t('Exclude from front page'),
      'path' => array(
        'pages' => array(
          '<front>',
        ),
        'visibility' => 0,
      )
    ),
    'exclude_landingpage' => array(
      'title' => t('Exclude from landing pages'),
      'path' => array(
        'pages' => array(
          'offer/*',
        ),
        'visibility' => 0,
      )
    ),
    'exclude_thankyou' => array(
      'title' => t('Exclude from thank you pages'),
      'path' => array(
        'pages' => array(
          'thank-you/*',
        ),
        'visibility' => 0,
      )
    ),
  );

  $structures['enterprise_conversion']['blocks'] = array();

  $structures['enterprise_conversion']['blocks']['cta:sel_cta_sidebar'] = array(
    'description' => t('Selector for sidebar CTAs'),
    'default' => array(
      'regions' => array('sidebar_second'),
      'visibility_presets' => array(
        'exclude_front',
        'exclude_landingpage',
        'exclude_thankyou',
      ),
      'weight' => 0,
    ),
    'visibility_presets' => $visibility_presets,
  );
  $structures['enterprise_conversion']['blocks']['cta:sel_cta_footer'] = array(
    'description' => t('Selector for footer CTAs'),
    'default' => array(
      'regions' => array('content'),
      'visibility_presets' => array(
        'exclude_front',
        'exclude_landingpage',
        'exclude_thankyou',
      ),
      'weight' => 0,
    ),
    'visibility_presets' => $visibility_presets,
  );


  $display_desc = array();
  if (module_exists('enterprise_blog')) {
    $view = views_get_view('enterprise_blog_blocks');
    if (!empty($view)) {
      foreach ($view->display AS $name => $display) {
        $display_desc['blog:' . $name] = isset($display->display_options['display_description']) ? $display->display_options['display_description'] : '';
      }
    }
    $structures['enterprise_conversion']['blocks']['views:enterprise_blog_blocks-recent'] = array(
      'description' => $display_desc['blog:recent'],
      'default' => array(
        'regions' => array('sidebar_second'),
        'visibility_presets' => array('enterprise_thankyou_content_type'),
      ),
      'visibility_presets' => $visibility_presets,
    );
    $structures['enterprise_conversion']['blocks']['views:enterprise_blog_blocks-popular'] = array(
      'description' => $display_desc['blog:popular'],
      'default' => array(
        'regions' => array('sidebar_second'),
        'visibility_presets' => array(),
      ),
      'visibility_presets' => $visibility_presets,
    );
    $structures['enterprise_conversion']['blocks']['views:enterprise_blog_blocks-related'] = array(
      'description' => $display_desc['blog:rel'],
      'default' => array(
        'regions' => array('content'),
        'visibility_presets' => array('enterprise_thankyou_content_type'),
      ),
      'visibility_presets' => $visibility_presets,
    );
  }

  return $structures;
}

/**
 * Implements hook_styler().
 *
 * Tell styler module what styles this module provides.
 */
//function enterprise_conversion_config_styler_style() {

//}
