<?php
/**
 * @file
 */

// TODO is there a better way of doing this? Can a libraries file called from
// .info?
function enterprise_extras_init() {
  drupal_add_js(drupal_get_path('module', 'enterprise_extras') . '/js/enterprise_extras.js');
  drupal_add_css(drupal_get_path('module', 'enterprise_extras') . '/css/enterprise_extras.css');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function enterprise_extras_form_menu_edit_item_alter(&$form, $form_state, $form_id) {
  $access = user_access('administer menu');

  $form['enterprise_extras'] = array(
    '#type' => 'fieldset',
    '#title' => t('Enterprise Extras'),
    '#description' => t('Options that can assist in theming.'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['enterprise_extras']['enterprise_mega'] = array(
    '#access' => $access,
    '#type' =>  'checkbox',
    '#title' => t('Mega Menu'),
    '#description' => t('Force this menu item to be a mega menu despite if it has children or not.'),
    '#default_value' => array_key_exists('enterprise_mega', $form['options']['#value']) ? $form['options']['#value']['enterprise_mega'] : 0,
    '#group' => 'enterprise_extras',
  );
  $form['enterprise_extras']['disable_icon_menu_block'] = array(
    '#access' => $access,
    '#type' =>  'checkbox',
    '#title' => t('Disable Icon for Menu Block'),
    '#description' => t('Icon API Menu will add icons to the menu all the time. Settings this will give the theme a chance to remove it.'),
    '#default_value' => array_key_exists('disable_icon_menu_block', $form['options']['#value']) ? $form['options']['#value']['disable_icon_menu_block'] : 0,
    '#group' => 'enterprise_extras',
  );
}


/**
 * Implements hook_menu_link_alter().
 */
function enterprise_extras_menu_link_alter(&$item) {
  
  if (isset($item['enterprise_mega']) && $item['enterprise_mega']) {
    $item['options']['enterprise_mega'] = $item['enterprise_mega'];
  } elseif (isset($item['enterprise_mega']) && $item['enterprise_mega'] == 0) {
    unset($item['options']['enterprise_mega']);
  }

  if (isset($item['disable_icon_menu_block']) && $item['disable_icon_menu_block']) {
    $item['options']['disable_icon_menu_block'] = $item['disable_icon_menu_block'];
  } elseif (isset($item['disable_icon_menu_block']) && $item['disable_icon_menu_block'] == 0) {
    unset($item['options']['disable_icon_menu_block']);
  }
}
